- src/theme/as24/index.ts
- src/theme/ms24/index.ts
- src/theme/shared/index.ts
- src/theme/shared/spacing.ts
- src/theme/stories/spacingShowcase.tsx
- src/theme/stories/theme.stories.mdx
References:
> Jira https://autoricardo.atlassian.net/browse/DM-169
> Figma https://www.figma.com/file/WmNmJ7jdB0Z7tOjj516nFB/AS24-Tokens?node-id=3%3A4
> Figma tokens https://github.com/smg-automotive/figma-tokens/blob/main/tokens.json
Setup of base theme SPACING tokens as defined in the design system.
* I found a mistake in the figma tokens json. I checked with Sergiu and he already fixed, now the key is `2xl` instead `xxl` and it is in sync with figma as well. 
* I was checking about the unit that we'll use in the spacing tokens case. And after checking with Sergiu we decided to go with `REM` for this case, for the font-size and line-height. If we use `PX` the values don't scale with browser font-size adjustments. Please let me know if I need to bring this topic into a discussion or if …
> feat: added spacing tokens in REM

- src/components/button/index.stories.mdx
- src/components/button/index.tsx
- src/themes/components/button.ts
- src/themes/shared/sizes.ts
- src/themes/shared/typography.ts
References:
[sizes-tokens in figma](https://www.figma.com/file/WmNmJ7jdB0Z7tOjj516nFB/AS24-Tokens?node-id=533%3A3)
[typography-token in figma](https://www.figma.com/file/WmNmJ7jdB0Z7tOjj516nFB/AS24-Tokens?node-id=25%3A93)
[Jira ticket]
1. After checking the button variations with Sergiu we found that we could remove one variation and unify and make more consistent our button component with ONLY two variations `md: 36px` and `lg: 48px`. Please be patience 🙏🏽 while we get our hands dirty we polish the work 🧼 and we make it more beautiful and perfect 🙌🏼
The following links on figma will be updated with the correct button size:
[ms24 button](https://www.figma.com/file/ZN4RxuKRVRHFEcN1xT00Kz/Components%3A-Web-MS24?node-id=2%3A860)
[as24 …
> BREAKING CHANGE: adjusted sizes & typography tokens

- src/themes/components/link.ts
- Reuse the pre-defined `typography` token as much as possible.
- Apply the `typography.body` for Link component
- There's no new visual change affected in this PR
> Refactor: reuse typography.body for link component

- src/components/index.ts
I missed exporting `stack` components from the package 🤦🏻  `formControl` was also not exported 🤦🏻 🤦🏻 
Also because I merged via VScode the commit wasn't semantic so the package wasn't released 🤦🏻 🤦🏻 🤦🏻 
Stack & FormControl were there but not released
Stack & FormControl are released and importable
> feat: release Stack component & export FormControl

- src/components/button/index.stories.mdx
- src/components/button/index.tsx
- src/themes/components/button.ts
References:
[Jira](https://autoricardo.atlassian.net/browse/DM-359)
[Figma](https://www.figma.com/file/CHU4fpMfXpiAW4qNFzi9y1/AS24-WebComponents?node-id=4%3A4226) -> Take into consideration: the secondary button styles apply in AS24 and MS24. The MS24 figma file needs to be updated. Therefore, check the AS24 file.
Add the secondary button styles.
No secondary button styles 😱
Secondary button is in place 🍹
Please check the branch locally.
> feat: added secondary button styles

- src/components/articleTeaser/__tests__/Index.Test.tsx
- src/components/articleTeaser/index.stories.mdx
- src/components/articleTeaser/index.tsx
- src/components/index.ts
- src/themes/components/articleTeaser.ts
- src/themes/components/index.ts
- src/themes/index.ts
- src/themes/shared/index.ts
- src/themes/shared/sizes.ts
References https://autoricardo.atlassian.net/browse/DM-362
Implements `ArticleTeaser` component
No article teaser 😱 
Play around with the article teaser in storybook
- we want to give flexibility on image sizing, but we want to have some control of the allowed sizes, hence new `size` values
- existing designs will be adapted to use provided values
- the entire teaser is a link, this was clarified with Enrique
- changed the spacing between the image and the content to be the same on mobile as on desktop. Confirmed with Enrique
> feat: ArticleTeaser component

- src/components/center/index.stories.mdx
- src/components/center/index.tsx
- src/components/fullHeight/index.stories.mdx
- src/components/fullHeight/index.tsx
- src/components/grid/index.tsx
- src/components/index.ts
https://autoricardo.atlassian.net/browse/FE-13
As preparation for adding the components package to the next example project 
- Extracts children for gird component props
- Exports centre chakra component (centres an element)
- Exports full height component ensuring the content uses the available height at minimum
Check the branch deployment or the integration in the next example project https://github.com/smg-automotive/next-example/pull/26
> Add utitily components

- src/components/button/index.tsx
References -
The button exposes different props for the onChnage handler than the chakra component which yields to issue when passing trough props from other components that use the same definition as the chakra component
> fix: button props

- src/components/fullHeight/index.stories.mdx
- src/components/fullHeight/index.tsx
- src/components/layout/BaseGrid.stories.mdx
- src/components/layout/BaseGrid.tsx
- src/components/layout/WithVehicleReference.stories.mdx
References "Meeting discussion"
- Storybook adds 16px padding by default which makes it difficult to grasp the intended design for the page layouts
- Design wants to see the base grid
no story for base grid and default padding
story for base grid and no default padding
1. check the layouts under "Layouts / Pages"
> feat: create new story for base grid and make it full height

- src/styles/Fonts.tsx
Relative URL was used for font loading which resulted in 404s when accessing nested paths.
> fix: use absolute url for fonts

- .storybook/preview.js
#201 changed how breakpoints are exported. This broke the storybook configuration that relied on private export.
> chore: fix storybook breakpoints switching

- src/components/articleTeaser/index.stories.mdx
- src/components/articleTeaser/index.tsx
- src/components/grid/index.stories.mdx
- src/components/layout/BaseGrid.stories.mdx
- src/components/layout/BaseGrid.tsx
- src/components/layout/TwoColumnsLayout.tsx
- src/components/section/index.tsx
- src/components/simpleHeader/index.tsx
- src/components/stack/index.stories.mdx
- src/components/vehicleReference/index.stories.mdx
- src/components/vehicleReference/index.tsx
- src/themes/components/simpleHeader.ts
- src/themes/components/vehicleReference.ts
- src/themes/shared/breakpoints.ts
- src/themes/stories/BreakpointShowcase.tsx
- src/themes/stories/SizeShowcase.tsx
- src/themes/stories/SpaceShowcase.tsx
- src/utilities/convertRemToPx.ts
- src/utilities/index.ts
Reference:
https://github.com/smg-automotive/listings-web/pull/38#issuecomment-1220742058
[Jira](https://autoricardo.atlassian.net/browse/DM-582)
[figma-breakpoint](https://www.figma.com/file/WmNmJ7jdB0Z7tOjj516nFB/AS24-Tokens?node-id=84%3A35) -> Note: Sancho is working on the clean up.
We are facing some overlapping issues in the break point 320px. We are still in an early stage where we can make this change without braking changes.
After the discussion with the designers we decided to go with the next breakpoints (please check the reason about adding them and in case that you have a concern/idea/suggestion please let us know. Nothing is set in a stone):
**Breakpoints:**
xxs: 320px.    REASON: we have traffic on this breakpoint
xs: 360px.      REASON: we have A LOT OF traffic on this …
> fix: breakpoint & word-break

- src/components/section/index.tsx
When passing an img and not an svg as a component, the image shrinks due to the max-width even if a larger width is applied to it.
It shrinks
It does not shrink anymore
> fix: image width for section

- src/components/divider/index.tsx
- src/components/layout/TwoColumnsLayout.stories.mdx
- src/components/layout/TwoColumnsLayout.tsx
- src/components/layout/WithVehicleReference.tsx
For [this](https://www.figma.com/file/f0LWQupJueW6KHBQujVGe4/Lead-Form-Page-(Working-Title)?node-id=511%3A64352) design, we need to pass a Section component as the page title. This requires us to allow a ReactNode to be passed and not only a string
Only string allowed
String and ReactNode allowed
> feat: allow ReactNode as layout title

- src/components/index.ts
- src/components/select/index.tsx
Export `Select` options type to use it outside of components pkg. Reference: https://github.com/smg-automotive/seller-web/pull/9
No exported options
Exported options exists
> fix: export select options type

- src/themes/components/link.ts
Fix the row on link. Thanks @lkappeler to raised this up.
Please check that the link with icons doesn't break into lines due to the content
> fix: fixed row

- src/components/link/index.stories.mdx
- src/themes/components/link.ts
> fix: display link as inline-flex

- src/components/formControl/__tests__/FormControl.Test.tsx
- src/components/formControl/index.tsx
References https://autoricardo.atlassian.net/browse/DM-678
We decided to show both a hint and an error message in case the field has an error.
> fix: show error message with the hint

- src/themes/components/select.ts
Fix arrow icon overlapping the text on the select.
Please check the select component and play around with the text.
> fix: arrow icon overlaps text

- package-lock.json
- package.json
- src/components/carousel/NavigationButton.tsx
- src/components/carousel/Slide.tsx
- src/components/carousel/__tests__/Index.Test.tsx
- src/components/carousel/index.stories.mdx
- src/components/carousel/index.tsx
- src/components/icons/ChevronLeftLargeIcon.tsx
- src/components/icons/ChevronRightLargeIcon.tsx
- src/components/icons/index.ts
- src/components/index.ts
References [DM-739](https://autoricardo.atlassian.net/browse/DM-739)
For the swiping gallery on the PDP, we need a carousel. In the [RFC](https://github.com/smg-automotive/au-docs/discussions/32) here we agreed on embla-carousel-react. In refinment we decided to have the component in the pkg to reuse it in the seller part too.
FYI: 
- pagination for the fullscreen gallery was not yet part of the ticket -> can be extended
- rendering multiple slides per slide for "similar cars" was not yet part of the ticket -> can be extended
No carousel
Carousel
https://talamcol-swiping-gallery.listings-web.branch.autoscout24.ch/de/d/8614365
https://talamcol-carousel.components-pkg.branch.autoscout24.ch/?path=/story/components-data-display-carousel--overview
> feat: carousel component

- src/components/energyLabel/index.stories.mdx
- src/components/energyLabel/index.tsx
- src/components/index.ts
References [DM-726](https://autoricardo.atlassian.net/browse/DM-726)
To display the efficiency of a car on the new PDP, we need an energy label component. Colors and sizing are not using the tokens, but those are given by the European commission, so we use those.
No energy label component
Energy label component
https://talamcol-energy-label.components-pkg.branch.autoscout24.ch/?path=/story/components-data-display-energy-label--energy-label
> feat: add new component for energy label

- src/components/center/index.tsx
- src/components/index.ts
- src/components/spinner/index.tsx
References N/A
Forgot to export the Spinner component.
Since I'm on it allowing padding on the Center component so I don't need to wrap a div for the spacing
> fix(Spinner): Export component

- src/components/checkbox/index.tsx
- src/components/datePicker/index.tsx
- src/components/input/index.tsx
- src/components/link/index.tsx
- src/components/radio/RadioListItem.tsx
- src/components/radio/index.tsx
- src/components/select/index.tsx
- src/components/textarea/index.tsx
References https://autoricardo.atlassian.net/browse/DM-826
`react-hook-form` relies on ref forwarding and uncontrolled inputs. To enable that we add `forwardRef` for input-like components that can be used in forms.
> fix: forward refs for input-like components & links

- src/components/icons/ChevronLeftSmallIcon.tsx
- src/components/icons/ChevronRightSmallIcon.tsx
- src/components/icons/index.ts
Left and right small chevron icons
N/A
https://boyarskiy-icons.components-pkg.branch.autoscout24.ch/?path=/story/foundations-icons--overview
> feat: add small chevron icons

- src/components/carousel/index.tsx
References https://autoricardo.atlassian.net/browse/DM-799
Adds previous/next navigation events on the left and right arrow keys respectively
- Interact with the fullscreen gallery in storybook
- For best results use the  link to open canvas in new tab:
> feat: arrow events on fullscreen carousel

- .circleci/config.yml
Add more resources for `release` job to prevent failing with an error:
```
FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
```
https://app.circleci.com/pipelines/github/smg-automotive/components-pkg/2369/workflows/dd51c921-f9e1-41fa-8776-c6688f0d0ba0/jobs/10967
small resources
medium resources
> fix: add more resources for release job

- src/components/grid/GridItem.tsx
- src/components/grid/index.tsx
- src/components/layout/app/Content.tsx
- src/components/layout/app/Footer.tsx
- src/components/layout/app/Header.tsx
For the new PDP, we need to whitelist even more props for the Grid components (sticky section on the right, full height, start position, different gaps for column and row etc.). Since this is a layout component similar to `Flex` or `Box` I don't see a reason to restrict it.
Subset of the chakra grid props
allow all chakra props
> feat: expose chakra props for Grid components

- src/components/devOverlay/__tests__/DevOverlay.Test.tsx
- src/components/devOverlay/index.stories.mdx
- src/components/devOverlay/index.tsx
- src/components/footer/config/__tests__/index.Test.ts
- src/types/brand.ts
Current activeTheme type doesn't work outside of package
We couldn't set `as24` or `ms24` as value for `activeTheme` prop 
We can set `as24` or `ms24` as `activeTheme` prop of `DevOverlay` component
> fix: DevOverlay activeTheme type

- src/themes/components/carousel.ts
- src/themes/components/menu.ts
- src/themes/components/switch.ts
We were hardcoding the opacity values instead using our tokens.
We were not able to used the `opacity` tokens as we are doing for the rest of the tokens like in colors -> `color: 'green50'`because chakra doesn't have any theme key for opacity. Besides we were using different units for opacity and it was not synced with our Design System.
I checked in the projects and we are using `opacity` only in the listings-web so far. I will adjusted it as well.
There is also another way to do it by `layerStyle` -> https://chakra-ui.com/docs/styled-system/text-and-layer-styles
but we could face an issue when we want to use it for something else than opacity and we end up with the element that has multiple
Opacity tokens didn't work and were not passed
We reference opacity as an object.
The opacity …
> fix: referenced opacity as an object

- src/components/pagination/__tests__/Pagination.Test.tsx
- src/components/pagination/index.tsx
Total pages shouldn't be increased by one, because of pagination API.
Pagination API starts from 0, but number of pages (length) doesn't change.
Pages: [0, 1, 2]
Total Pages: 3
Wrong total pages
Correct total pages
https://boyarskiy-pagination-fix.components-pkg.branch.autoscout24.ch/?path=/story/patterns-navigation-pagination--pagination
> fix(pagination): fix total pages

- src/components/link/index.tsx
https://autoricardo.atlassian.net/browse/VSST-722
Using Link component in combination with NextLink caused infinite re-rendering and return an error:
```
<NextLink href="/" passHref={true}>
<Link>some link</Link>
</NextLink>
```
```
Uncaught [Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.]
```
After research, it looks like it is related to forwardRef, somehow the component re-creates itself in a loop.
I wrapped component creation with `useMemo` to prevent re-creation when `as` is the same.
PS: didn't find solution for other issue that props autocomplete does not work in IDE.
Link component wrapped with NextLink didn't …
> fix(Link): infinite loop when wrapped with NextLink

- src/components/button/index.tsx
ariaLabel and icon were spread in the `rest` object on the component. Because they are no chakra props, they are not filtered out. This results in invalid HTML:
> fix: invalid html attributes for button

- src/themes/components/form.ts
https://autoricardo.atlassian.net/browse/VSST-759
Change color for required indicator to red.
Required indicator is grey
Required indicator is red
> fix: collor of required indicator

- src/components/pagination/PaginationButton.tsx
- src/components/pagination/index.tsx
Prevent default event on click
Without preventing default onClick event caused refreshing the page
Prevents unexpected page refresh and works correctly
> fix(pagination): prevent default on click event

- src/components/layout/app/AppLayout.tsx
References [VSST-754](https://autoricardo.atlassian.net/browse/VSST-754?atlOrigin=eyJpIjoiODBlMzg2Zjg3NDQ2NDY2ZDlmYmQzNGQ5MWY3MWM2YzAiLCJwIjoiaiJ9)
Font family should be `Make it Sans` everywhere and it is not always the case (at least in seller-web).
Some components don't return the right font. 
From what I understood it is especially linked to the `Text` component: if we don't pass a `textStyle` props, the font is not applied. 
I applied the base style to the AppLayout to make sure we always have the right font everywhere
You can have a look at [this PR](https://github.com/smg-automotive/seller-web/pull/209)
> fix: font family in body

- src/components/devOverlay/__tests__/DevOverlay.Test.tsx
- src/components/devOverlay/index.tsx
References [VSST-857](https://autoricardo.atlassian.net/browse/VSST-857?atlOrigin=eyJpIjoiZWQ4YzI2Mjc1MDY5NDBmNDlhNjQ2OWEzYmY0NzU1YTYiLCJwIjoiaiJ9)
This PR combined with [this one](https://github.com/smg-automotive/i18n-pkg/pull/79) and [this one](https://github.com/smg-automotive/seller-web/pull/217) allows a better and easier cooperation with translation by returning the keys instead of translations. We can now have a switcher for this in the DevOverlay component.
No possibility to check upon the keys easily
Possible to check the translation keys in local and int env
You can check with [this link](https://marine-test-key-translation-seller-web.branch.autoscout24.dev/en/insertion/identify) that the switcher for translation is visible in `devOverlay` and that it works as intended.
> feat: add translation switcher

- src/components/vehicleReference/index.stories.mdx
- src/components/vehicleReference/index.tsx
According to backend, only id, make, sellerId and vehicleCategory are mandatory on listing.
Props are mandatory
Props are optional
> fix: make vehicle reference props optional

- src/components/checkbox/index.tsx
- src/components/formControl/index.stories.mdx
- src/components/formControl/index.tsx
- src/components/formLabel/index.stories.mdx
- src/components/formLabel/index.tsx
- src/themes/components/checkbox.ts
- src/themes/components/formLabel.ts
References https://autoricardo.atlassian.net/browse/VSST-873
We should be able to choose between `small` and `large` sizes for `FormControl` and `Checkbox` components. With this MR we are adding `size` prop for those components.
https://www.figma.com/file/CHU4fpMfXpiAW4qNFzi9y1/11.-AS24---Web---Components?node-id=55%3A3221&t=T3ICxm84xQl7q1DD-0
Without possibility to choose size.
We can pass value for size prop -  `sm` | `lg`
https://zbiljic-vsst-873-components-pkg.branch.autoscout24.dev/?path=/story/components-forms-form-label--form-label
> feat: adding size prop to FormControll & Checkbox

- src/components/layout/BaseLayout.tsx
Turns out, the ad container is not always sticky. For instance, on the detail page it is not, on the search page it is. Let the usage define the sticky behavior and not the component.
> fix: remove sticky from ad container

- src/components/input/index.stories.mdx
- src/components/input/index.tsx
References https://autoricardo.atlassian.net/browse/VSST-898
We need to use Input component with type `number` for some of the fields inside seller-web repo (mileage, price etc.). In order to achieve that we have to extend Input component with `type` prop.
No `type` prop on Input component
We can set type prop.
https://zbiljic-vsst-989-extend-input-props-components-pkg.branch.autoscout24.dev/?path=/story/components-forms-input--overview&args=type:number
> fix: extending Input with type prop

- src/components/textarea/index.stories.mdx
- src/components/textarea/index.tsx
In order to change text style for textarea component, we have to add textStyle props.
N/A
textStyle prop is available
> feat: add text style to textarea

- src/lib/cli/setupNextFonts/template.tsx
The font configuration template referenced a bold font as a regular font.
The same file was also referenced twice. I believe this was the reason for the font not loading correctly.
> fix: bold font referenced as regular

- src/components/simpleGrid/index.tsx
If we need to set width to SimpleGrid we need to do sth like `<Box as={SimpleGrid} w="full" />`
SimpleGrid does not have width prop
Use <SimpleGrid w="full />
> feat: add 'width' to SimpleGrid component

- src/components/checkboxGroup/index.stories.mdx
- src/components/checkboxGroup/index.tsx
Missing key prop on `CheckboxGroup` component
N/A
We have `key` prop on `CheckboxGroup` fragment
> fix: adding key prop to checkbox group fragment

- src/components/accordion/AccordionIcon.tsx
- src/components/mobileOnlyAccordion/MobileOnlyAccordionButton.tsx
- src/components/mobileOnlyAccordion/MobileOnlyAccordionItem.tsx
- src/components/mobileOnlyAccordion/MobileOnlyAccordionPanel.tsx
- src/components/mobileOnlyAccordion/__tests__/MobileOnlyAccordion.Test.tsx
References https://autoricardo.atlassian.net/browse/VSST-871
Using window.matchMedia leads to issues with the legacy integrations
https://github.com/chakra-ui/chakra-ui/issues/4319#issuecomment-878237998
Uses CSS instead of matchMedia to show/hide the mobileOnlyAccordion
Ensure the Mobile only accordion works
> fix(Accordion): render CSS based instead of conditional

- src/components/footer/config/index.ts
We found a missing link for IT lang during the integration footer into legacy.
> fix(footer): missing link for IT lang

- renovate.json
References https://autoricardo.atlassian.net/browse/FE-88
Releases of multiple UI-related dependencies cause multiple releases of components package since all of them are merged separately.
This PR groups the patch and minor releases of those dependencies to reduce the version noise on the components package
> chore: group ui related dependency updates

- src/components/text/index.tsx
References
Instead of using Box as={Text} for truncation, we should pick `isTruncated` prop. Similar prop is noOfLines. 
No truncation.
With truncation prop.
With noOfLines prop
> fix: add truncated and noOfLines prop to Text comp

- src/components/rangeFilterInput/InputGroup.tsx
- src/components/rangeFilterInput/__tests__/Index.Test.tsx
- src/components/rangeFilterInput/index.stories.mdx
- src/components/rangeFilterInput/index.tsx
- src/themes/components/numberInput.ts
References https://autoricardo.atlassian.net/browse/DM-1178
Adds debounce of 1 second (debatable) for range input filter because it would be too heavy on BE side on each keystroke. Also added onBlur param.
Also some style fixes based on latest design updates.
No debounce on range input filter. No onBlur param option.
1 second debounce option on filter input. onBlur option.
After entering input should be 1 second delay in action tab on storybook.
> Fix range filter

- src/components/missingImage/index.tsx
- src/themes/shared/colors.ts
References
Notion - gray color: https://www.notion.so/smgnet/Review-light-grey-colors-828e4dab90ce4b1ba12a85f0f436af45
Notion - missing image size icon: https://www.notion.so/smgnet/Missing-image-icon-9396c3d7eb0948d686b495855581fb36
> fix: gray color & missing image size

- src/components/index.ts
- src/components/topListingBadge/index.stories.mdx
- src/components/topListingBadge/index.tsx
References https://autoricardo.atlassian.net/browse/VSST-985
As a part of the implementation of product cards, we want to show product previews - in this particular case a top-listing badge.
Since this is a component that will be used on the SRP as well it makes sense to share it from the start
> feat: top listing badge component

- src/components/flex/index.tsx
- src/components/footer/Companies.tsx
References https://autoricardo.atlassian.net/browse/DM-1208
Please check the next points:
* We must not be able to pass the properties `gap`, `columnGap` and `rowGap`
https://github.com/smg-automotive/listings-web/pull/639/files
* The footer looks as before in the companies section (check all breakpoints)
* In seller project I just find one place were we are using gap. I will open a PR for it.
> BREAKING CHANGE: ignored some flex properties

- src/components/icons/WarningIcon.tsx
- src/components/icons/index.ts
Adds a `WarningIcon` needed to implement error messages on product cards:
> feat: add warning icon

- src/components/heading/index.tsx
References [DM-1427](https://autoricardo.atlassian.net/browse/DM-1427)
as per [WCAG 2.0](https://www.w3.org/TR/2012/NOTE-WCAG20-TECHS-20120103/G141), it's important to follow proper nesting on the page (h2 after h1 etc.). To meet our design requirements, it happens that a heading that is for example a h3 as per nesting, should look like an h4.
textStyle is not allowed
textStyle is allowed
-
[DM-1427]: https://autoricardo.atlassian.net/browse/DM-1427?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: whitelist textStyle for heading components

- src/components/list/OrderedList.stories.mdx
- src/components/list/UnorderedList.stories.mdx
- src/themes/components/list.ts
If you open https://main-components-pkg.branch.autoscout24.dev/?path=/story/components-data-display-list-unordered-list--unordered-list in Firefox, you can see that there is no space between the bullet point and the list item text. This is caused by the margin we overwrite in the styles. This PR addresses the following issues:
1. removing the margin for the inside variant. This was not needed and caused the bullet points and text being too close to each other
2. setting the margin for the outside variant to 1em (same as chakra has by default: https://github.com/chakra-ui/chakra-ui/blob/main/packages/components/layout/src/list.tsx#L107, but it's only needed for outside)
FYI: there is a bug in chromium browsers, nothing we can do there:
- …
> fix: list style for unordered and ordered list

- src/components/popoverFilter/ActionButton.tsx
- src/components/popoverFilter/props.ts
References [DM-1442](https://autoricardo.atlassian.net/browse/DM-1442)
Since we apply search realtime when a filter is changed, the onClick handler of the action button is usually not needed. 
Passing onClick={()=> null}
onClick is now optional and does not have to be passed
[DM-1442]: https://autoricardo.atlassian.net/browse/DM-1442?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: make onClick optional for popover action button

- src/components/link/index.stories.mdx
- src/components/link/index.tsx
References https://autoricardo.atlassian.net/browse/DM-968
To be able to pass the next `rel` and `target` as the image showed we need to make target and rel approachable.
Please check the las 2 variations from the Link component
> fix: adjusted target and rel in link

- src/components/icons/ChevronUpSmallIcon.tsx
References N/a
The icon points the wrong way
> fix(Icon): make the chevron up icon point to the right direction

- src/components/navigation/header/index.tsx
Header had css `position: absolute` and because of that parent element has no height and as a result we have broken layout.
> fix: header css position

- src/components/text/index.tsx
- src/themes/stories/BorderRadiusShowcase.tsx
- src/themes/stories/TypographyShowcase.tsx
References
> Slack discussion:  https://automotivesmg.slack.com/archives/C034EGP8GG0/p1680175774281809
I will go through all the components we have so far and give the flexibility to taking all the style props that the component offers BUT taking into consideration the DS, in some components we must restrict some props styles. 
After I merge this change I will make a clean up in all the projects, removing the extra wrappers we added, making the DOM cleaner. Wait for the PRs...
Note: this is not a breaking change.
The text component picked some style props
The text component takes all the style props without any restriction.
> fix: accepted all style props

- src/components/tooltip/__tests__/Tooltip.Test.tsx
- src/components/tooltip/index.tsx
References [FE-142](https://autoricardo.atlassian.net/browse/FE-142)
Chakra-ui Tooltip is not created for touch screens. It was created for hover state. We are wrapping their comp and just omit some props.
No support for touch screens.
Support touch screens.
- Open branch dev storybook. 
- Find Tooltip.
- Switch to mobile mode in browser dev.
- Try to open and close tooltip label via press.
[FE-142]: https://autoricardo.atlassian.net/browse/FE-142?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: enable tooltiop close/open on touch screens

- src/components/navigation/footer/index.tsx
- src/components/navigation/header/NavigationAvatar.tsx
- src/components/navigation/header/NavigationItems.tsx
- src/components/navigation/header/drawer/index.tsx
- src/components/navigation/header/index.tsx
- src/themes/shared/sizes.ts
Adding max-width for navigation containers (header & footer). Minor lighthouse improvements.
> fix: header&footer container width & lighthouse improvements

- src/components/icons/ChevronUpLargeIcon.tsx
References [VSST-1200](https://autoricardo.atlassian.net/browse/VSST-1200)
Current icon is too big in the accordion. It needs to be replaced with a smaller one
Check if the icon is smaller on a accordion
[VSST-1200]: https://autoricardo.atlassian.net/browse/VSST-1200?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: change chevron icon

- src/components/accordion/AccordionIcon.tsx
- src/components/icons/ChevronUpLargeIcon.tsx
- src/components/icons/ChevronUpSmallIcon.tsx
References [VSST-1200](https://autoricardo.atlassian.net/browse/VSST-1200)
Checked with the designer and decided to change the Accordion to ChevronUpSmallIcon and 
the ChevronUpSmallIcon to the attached design file. 
Current icon is too big in the accordion. It needs to be replaced with a smaller one
Check if the icon is smaller on a accordion
[VSST-1200]: https://autoricardo.atlassian.net/browse/VSST-1200?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: chng chevron small icon according to design

- src/components/layout/BaseLayout.tsx
- src/components/layout/TwoColumnsLayout.tsx
- src/components/layout/WithVehicleReference.stories.mdx
- src/components/layout/WithVehicleReference.tsx
- src/components/vehicleReference/index.tsx
References https://autoricardo.atlassian.net/browse/VSST-1193
In order to reuse `LayoutWithVehicleReference` on `SuccessPage` we have to extend component with additional props.
- no call to action button
- header required
https://zbiljic-vsst-1193-components-pkg.branch.autoscout24.dev/?path=/story/layout-pages-layout-with-vehicle-reference--without-header
> feat: extending LayoutWithVehicleReference component

- src/components/navigation/footer/index.tsx
Adjust horizontal padding for the footer container.
too big padding
aligned with logo in the header:
> fix: adjust footer section padding

- src/components/navigation/footer/config/index.ts
References https://autoricardo.atlassian.net/browse/VSST-1256
Our newsletter signup form is not protected by a captcha. It looks like currently, it’s generating a lot of fake registrations. The temporary measure is to take the current registration form down and replace it with the new version developed by marketing later (when ready)
No `Newsletter` link in footer
https://zbiljic-vsst-1256-remove-newsletter-link-components-pkg.branch.autoscout24.dev/?path=/docs/patterns-navigation-footer--docs
> fix: removing newsletter link from footer

- src/themes/components/modal.ts
- src/themes/shared/zIndices.ts
[IN-681](https://autoricardo.atlassian.net/browse/IN-681?atlOrigin=eyJpIjoiYjE4YWRkMWFjNTIyNGU1M2JiNjU5MzNmOWYxYjk5Y2QiLCJwIjoiaiJ9)
zIndex of Header was > than zIndex of fullScreenModal
Header is hidden
This bug was visible on Firefox (and maybe others), not Chrome.
You can check with this link: https://fix-modal-seller-web.branch.autoscout24.dev/de/insertion/car/100000243/images
[IN-681]: https://autoricardo.atlassian.net/browse/IN-681?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: fullScreen modal zindex

- src/themes/components/carousel.ts
Improvements for [IN-681](https://autoricardo.atlassian.net/browse/IN-681?atlOrigin=eyJpIjoiZmExMWQxNjgxN2ZmNDg2ODkxZTk1OGZkZWEzMzU2NGEiLCJwIjoiaiJ9) following QA's review, [here](https://github.com/smg-automotive/seller-web/pull/530#issuecomment-1552616082)
On focus on the gallery button, a white border is displayed
White border on focus
No white border
https://marine-improve-gallery-components-pkg.branch.autoscout24.dev/iframe.html?args=&id=components-data-display-carousel--full-screen&viewMode=story
[IN-681]: https://autoricardo.atlassian.net/browse/IN-681?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: white border on focus in carousel

- src/components/checkbox/index.tsx
- src/themes/components/checkbox.ts
Add variants to the checkbox to align elements by top and center. They are centered by default.
**Center:**
**Top:**
> fix(checkbox): add variants to align elements by top and center

- src/components/icons/ExchangeIcon.tsx
References [DM-1746](https://autoricardo.atlassian.net/browse/DM-1746)
Icon had extra space on the right side
[DM-1746]: https://autoricardo.atlassian.net/browse/DM-1746?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: echange icon

- src/components/layout/TwoColumnsLayout.tsx
- src/components/layout/WithVehicleReference.tsx
So that we can support client side routing within the new stack as well as full redirects to the legacy, we need to be able to pass in NextLink, normal Links or buttons with click handlers. Because of that, I enabled passing a ReactNode to the layout.
> feat: allow react node for backlink

- src/components/navigation/footer/Apps.tsx
References https://autoricardo.atlassian.net/browse/DM-1800
Links for mobile apps where clickable outside of their image length. 
You could click on footer mobile links outside of the box. And depending on screen size it can be smaller/larger
Clickable only on image
Try to click on mobile app links outside of their images in the footer.
> fix: mobile apps link display

- src/components/layout/BaseLayout.tsx
- src/components/layout/app/Content.tsx
References 
https://autoricardo.atlassian.net/browse/DM-1754
Not enough spacing between footer and content. 
We are currently using spacing (padding) on the `<main>` element but adding it there (expanding) would not solve the issue on PDP for example because we have sticky lead button then goes outside of the <main>. That is just one example.
That is the reason I went with the `content layout` component, to try and simplify solution so that we don't have too much changes in some other components to accommodate this change. One thing I noticed so far, that we will need to remove `margin-bottom`s from our components in the other projects, specially in case if they are last elements.
[Describe the new behavior and …
> fix: margin between content and footer component

- src/themes/components/button.ts
References https://autoricardo.atlassian.net/browse/DM-1834
In order to have a better contrast ratio, a black font color together with the ms24 red background color improves accessibility.
After checking with the UX-designers. They decided to change the text color in AS24 as well.
> fix: changed color text

- src/components/filterPatterns/modal/__tests__/Index.Test.tsx
- src/components/filterPatterns/modal/index.stories.mdx
- src/components/filterPatterns/modal/index.tsx
- src/components/filterPatterns/popover/Popover.tsx
- src/components/filterPatterns/popover/__tests__/Index.Test.tsx
- src/components/filterPatterns/popover/index.stories.mdx
- src/components/filterPatterns/popover/index.tsx
- src/components/filterPatterns/props.ts
References https://autoricardo.atlassian.net/browse/DM-1809
For the make model filter, we need to be able to pass a custom filter header and to toggle the visibility of the action button.
https://www.figma.com/file/WvYYKrx8rxw80fwkzhAQwh/Search-Results-%26-Advanced-Search?node-id=1174%3A244074&mode=dev
Fixed header and action button is always shown
Button and header can be customized
https://talamcol-custom-filter-header-components-pkg.branch.autoscout24.dev/?path=/story/patterns-filter-modal--with-custom-header
https://talamcol-custom-filter-header-components-pkg.branch.autoscout24.dev/?path=/story/patterns-filter-modal--without-call-to-action-button
https://talamcol-custom-filter-header-components-pkg.branch.autoscout24.dev/?path=/story/patterns-filter-popover--without-call-to-action-but …
> feat: custom filter header

- src/components/navigation/footer/Link.tsx
- src/components/navigation/footer/config/__tests__/index.Test.ts
- src/components/navigation/footer/config/index.ts
References [DM-1828](https://autoricardo.atlassian.net/browse/DM-1828)
Current twitter account does not belong to our company. We decide to remove icon button link for twitter in case of motoscout brand.
Twitter icon link to twitter account 
No twitter link for motoscout
[DM-1828]: https://autoricardo.atlassian.net/browse/DM-1828?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> remove twitter account from motoscout

- src/themes/components/select.ts
References https://www.notion.so/smgnet/the-dropdown-icon-in-Select-component-should-be-more-to-the-right-0fca177dd7f948c28f773ee4ffc85db5
There is 12 px margin right but because of the spacing inside the icon it adds up and ends up with too much empty space on the right.
> fix: adjusted right margin

- src/themes/components/link.ts
References https://www.notion.so/smgnet/Unify-correct-standardise-spacings-between-icon-and-label-in-BUTTON-and-LINK-component-e01723ba4ef34a32999fca07bf8d3bb9
Adjust margins in links
> fix: adjusted margins

- src/components/button/index.stories.mdx
- src/components/button/index.tsx
- src/themes/components/button.ts
References [[link the ticket here](https://autoricardo.atlassian.net/browse/DM-1971)]
We need variation for icon button that is transparent (basically without border). One consideration was to have some sort of prop `disable/removeBorder` but then we would need to pass border styles for buttons that are using it. I prefer this way but open for change/adjustment.
> fix: add transparent button variant

- src/components/checkbox/index.tsx
- src/components/checkboxGroup/index.tsx
- src/themes/components/checkbox.ts
Add variant property to Checkbox Group.
N/A
Variant property exists for checkbox group.
> fix: add variant to checkbox group

- src/themes/components/pagination.ts
References https://www.notion.so/smgnet/Review-Pagination-component-in-the-insertion-2f391a7358ce4db8b8c2e099bd2ebfd4
Add background color to the active pagination buttons
Check the corresponding color as in the figma design when pressing the pagination button
> fix: adjusted the pressed state color

- src/components/topListingBadge/index.tsx
- Based on the rebranding, the color for MS24 should be black and not white
- the current implementation does not work with the carousel because of the aspect ratio
- carousel is not usable because the badge covers the pointer events
https://github.com/smg-automotive/listings-web/pull/1345
> fix: top listing badge

- src/components/pagination/index.tsx
https://autoricardo.atlassian.net/browse/IN-1265
The active number in the pagination should always be in the center so the user can select previous and next page either with the number or the arrow button.
https://fix-pagination-components-pkg.branch.autoscout24.dev/?path=/docs/patterns-navigation-pagination--docs
> fix: render active number in the center

- src/components/navigation/link.ts
After updating component-pkg version to [20.7.8](https://github.com/smg-automotive/components-pkg/pull/739), internal links in production were broken.
It was because `useAbsoluteUrl` is always false in production so we would not go through the logic for internal links.
> fix: useAbsoluteUrl

- src/themes/components/button.ts
References [JIRA ticket](https://autoricardo.atlassian.net/browse/FE-184)
When using a transparent button variant in a component that has its own background colour, the button shows white background and on hover its background differs from the parent component.
Transparent button variant shows white background as a default state.
Transparent button variant shows transparent background as a default state.
Use Storybook to access button variants and confirm it works as expected.
https://autoricardo.atlassian.net/browse/FE-184
> fix: remove transparent button variant bg color

- src/components/navigation/header/config/DrawerNodeItems.tsx
References https://autoricardo.atlassian.net/browse/VSST-1600
Before the insertion flow release we want to make sure there are no links to checkout page. There is a difference between new (replatformed) and legacy checkout page, therefore we are removing link from navigation.
Link to checkout page in navigation.
No checkout link in navigation.
> fix: hide checkout navigation item

- src/components/navigation/header/config/DrawerNodeItems.tsx
Since we don't support last searches once we release the new SRP, we need to remove it. I checked with Raluca and it's ok to remove it from production MS24 as well. We'll still have the link on the search box on home until the day of the release
> feat: remove last searches for MS24

- src/components/navigation/BaseConfig.tsx
- src/components/navigation/header/config/HeaderNavigationConfig.tsx
- src/components/navigation/header/index.tsx
BE services are returning a lot of entitlements that are not related to header navigation. In order to avoid casting /exporting `Entitlements` type from components-pkg and adding all unnecessary entitlements to components-pkg we will accept array of strings for entitlements prop. This will not affect components-pkg in any way, because we have entitlements defined and we are doing check based on that definition.
> fix: entitlements prop type

- src/components/index.ts
- src/components/topVehicleSharedBadge/index.stories.mdx
- src/components/topVehicleSharedBadge/index.tsx
- src/themes/autoscout24/index.ts
- src/themes/motoscout24/index.ts
Adds a badge used for shared top vehicle slot.
The intention is to replace the uploaded image with a component.
Design https://www.figma.com/file/hMOmjeR3dH6k0eNzwX1G5T/TopCars?node-id=563%3A19803&mode=dev
> feat: top vehicle badge

- src/components/navigation/header/config/DrawerNodeItems.tsx
- src/components/navigation/header/config/HeaderNavigationConfig.tsx
- src/components/navigation/link.ts
References https://autoricardo.atlassian.net/browse/VSST-1741
Instead of requiring only one entitlements to display link, we are now able to require one of provides entitlements.
Only one required entitlement
Requring ony of entitlements in defined in `singleRequiredEntitlement` array.
> fix: required entitlements array

- src/components/navigation/header/config/DrawerNodeItems.tsx
- src/components/navigation/header/config/HeaderNavigationConfig.tsx
- src/components/navigation/header/index.stories.mdx
- src/components/navigation/link.ts
- src/locales/de/dict.json
- src/locales/en/dict.json
- src/locales/fr/dict.json
- src/locales/it/dict.json
- src/types/entitlements.ts
References https://autoricardo.atlassian.net/browse/VSST-1364
We should display different translation for `Toplisting` link based on entitlements user have.
Displaying `Toplisting` or `ToplistingPro` link text depending on user entitlements.
https://zbiljic-toplisting-entitlements-components-pkg.branch.autoscout24.dev/
- go to header navigation story
- add or remove `listing-visibility-standard` or `listing-visibility-premium` entitlement using story controls and observe changes to the `Toplisting` item inside drawer menu
> fix: toplisting entitlement

- src/components/rangeFilterInput/InputGroup.tsx
Iphones do zoom in when an input field is focussed. This is the case when the fontSize of the input field is set to something else than 1rem. `body` didn't even exist. This makes the text a bit bigger, but it was wrong anyway. Based on the design it should be 16px
> fix: iphone zoom on input focus

- .storybook/main.ts
Hide chakra components from storybook to reduce confusion.
Let me know if it’s a bad idea :smile:
Chakra components presented in storybook
Only our components presented in storybook
https://chore-disable-chakra-components-pkg.branch.autoscout24.dev/
> chore: hide chakra components from storybook

- src/themes/components/link.ts
References [[link the ticket here](https://autoricardo.atlassian.net/browse/DM-2450)]
This PR changes the default disabled color for links. Based on the latest design changes, we should have disabled link color to gray.500
Disabled link color anywhere should be gray.500
> fix: disabled link color

- src/components/devOverlay/index.tsx
- src/components/index.ts
- src/components/switchComponent/index.stories.mdx
- src/components/switchComponent/index.tsx
References [VSST-1637](https://autoricardo.atlassian.net/browse/VSST-1637)
The top vehicle management page has switches used for prioritising specific listings.
Done:
- exposed switch component
- changed switch component default variant to be default instead of `themeSwitch`
- explicitly set `themeSwitch` variant where it was implicitly set before
- added variant change in story
Switch component is not available to external projects.
Switch component is available to external projects.
Check if the component can be imported in an external project.
[VSST-1637]: https://autoricardo.atlassian.net/browse/VSST-1637?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: expose switch component

- src/components/navigation/header/config/DrawerNodeItems.tsx
[IN-1383](https://autoricardo.atlassian.net/browse/IN-1384?atlOrigin=eyJpIjoiMWRkNDIxZDZjMDUyNGUzN2E1ZmI0Mzg2OTgwZjE1NWYiLCJwIjoiaiJ9)
In the header, the utm_campaign is wrong for Insurance comparison
The insurance comparison links in the header return `subnavigation_moto_ instead` of `subnavigation_car_` for MS24
Please make sure the UTM param is correct for both private and professional: https://in-1384-components-pkg.branch.autoscout24.dev/?path=/story/patterns-navigation-header--professional
Thank you 🍂 
[IN-1383]: https://autoricardo.atlassian.net/browse/IN-1383?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: UTM param for insurance comparison header

- src/components/filterPatterns/modal/index.tsx
- src/components/filterPatterns/popover/Popover.tsx
References https://autoricardo.atlassian.net/browse/DM-2444
On Windows (or Mac with external windows mouse) users see scrollbars on the filter even if they are not needed.
https://talamcol-filter-scrollbar-listings-web.branch.autoscout24.dev/de/s
> fix: change overflow to auto for popover and modal filter

- src/components/rangeFilterInputWithSlider/index.tsx
- src/components/rangeSlider/RangeSliderWithChart.tsx
References https://github.com/smg-automotive/listings-web/pull/1612#pullrequestreview-1731948544
1. go to https://main-components-pkg.branch.autoscout24.dev/?path=/docs/components-filter-range-filter-input-with-slider--docs
2. edit the `to` field to be something that is not selectable via the slider (e.g. 10006)
3. grab the slider and change the `from` value
4. you'll notice that the `to` value changes while sliding and resets to 10006 after the slider is released
Fixed
> fix: range input value while sliding

- src/components/rangeSlider/RangeSliderWithChart.tsx
To avoid layout shifts, we reserve the space for the histogram and the slider
> fix: set height of chart to avoid layout shifts

- src/components/rangeSlider/RangeSliderWithChart.tsx
If facets are an empty array (which is possible since it's a BE response), this throws an error:
https://app.datadoghq.com/logs?query=status%3Aerror%20kube_namespace%3Aprod%20service%3A%2A-web&agg_m=count&agg_q=service&agg_t=count&cols=host%2Cservice&event=AgAAAYvwx6WaRrKiUAAAAAAAAAAYAAAAAEFZdnd4NjVEQUFCSWdhVFQtV0xMNXdCRQAAACQAAAAAMDE4YmYwYzctYmFjMC00NGQyLTk2N2EtODdjZGU1NTY2MjQz&index=main&messageDisplay=inline&panel=%7B%22queryString%22%3A%22service%3Alistings-web%22%2C%22filters%22%3A%5B%7B%22isClicked%22%3Atrue%2C%22source%22%3A%22tag%22%2C%22path%22%3A%22service%22%2C%22value%22%3A%22listings-web%22%7D%5D%2C%22queryId%22%3A%22a%22%2C%22timeRange%22%3A%7B%22from%22%3A1700551690000%2C%22to%22%3A1700551700000%2C%22live%22%3Afalse%7D%7D&refresh_mode=slidin …
> fix: calling reduce with no initial value

- src/components/rangeFilterInput/InputLeftElement.tsx
References
> Bug ticket https://autoricardo.atlassian.net/browse/DM-2505
> Figma https://www.figma.com/file/WvYYKrx8rxw80fwkzhAQwh/Search-Results-%26-Advanced-Search?type=design&node-id=5803-214515&mode=design&t=vk3EFEUKsPXUrLzF-0
We give more space to the left element in  the range input for filters.
Please check the range input
> fix: adjusted left element on range filter

- src/hooks/index.ts
- src/hooks/useBreakpointValue.ts
- src/hooks/useToken.ts
Re-exports `useBreakpointValue`  and `useToken` hooks from chakra
Not all props use the responsive value syntax (eg. divider doesn't), this hook is built to assign a different value based on a breakpoint and helps in such cases
This hook is made to access tokens and helps us when styling 3rd party components (eg. charts)
> feat: export utility hooks

- src/components/filterPatterns/Heading.tsx
- src/components/filterPatterns/modal/index.tsx
- src/components/filterPatterns/popover/index.tsx
- src/components/filterPatterns/props.ts
The new requirement is that the reset button on the popover should not immediately reset the filters. The one on the filter button does. This also differs between SRP and advanced search. If we now which reset button was pressed, it allows us to make that behavior.
> feat: return button position on reset

- src/components/drawer/DrawerContent.tsx
References [JIRA](https://autoricardo.atlassian.net/browse/IN-1073)
While implementing drawer component for VP card, we noticed that close button is too small.
Close button very small (8px).
Close button medium (14px, more clickable).
Test from Storybook: `?path=/story/components-data-display-drawer--drawer&args=withCloseButton:!true`
> chore: increase drawer close button

- src/components/icons/ChartIcon.tsx
- src/components/icons/index.ts
References [VSST-1945](https://autoricardo.atlassian.net/browse/VSST-1945)
- added `chart crossed` icon required for top vehicle management page statistics modal
- svg optimized via https://svgoptimizer.com/ (reduced size by ~25% compared to figma export)
No `chart` icon.
https://chart-icon-components-pkg.branch.autoscout24.dev/?path=/story/foundations-icons--icons
[VSST-1945]: https://autoricardo.atlassian.net/browse/VSST-1945?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: chart icon

- src/components/tooltip/index.stories.mdx
- src/components/tooltip/index.tsx
This reverts commit 0a7847ea31f8d536704c53791209f855c0f94d9d.
References [JIRA](https://autoricardo.atlassian.net/browse/IN-1536)
Revert the Tooltip changes due to an UI breaking change: Portals get rendered as `div`, which breaks a layout where it is used inline with a text.
> "fix: revert override for tooltip stacking order (#873)"

- src/components/layout/SingleColumnCentered.tsx
References [VSST-1918](https://autoricardo.atlassian.net/browse/VSST-1918)
The private seller insertion flow packages page content width is wider than what is currently configured. This PR adds the ability to customize the insertion layout max width via prop.
Insertion flow layout max width must be `md`.
Insertion flow layout max width is customizable via prop.
[VSST-1918]: https://autoricardo.atlassian.net/browse/VSST-1918?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: expose SingleColumnCentered max content width prop

- src/themes/components/tooltip.ts
- src/themes/shared/zIndices.ts
References https://autoricardo.atlassian.net/browse/IN-1536
Tooltips are not visible when rendered within a drawer component
Tooltip not visible
Check the tooltip is visible within the drawer
> fix: z-index for tooltips

- .github/workflows/lint-i18n-files.yml
[FE-180](https://autoricardo.atlassian.net/browse/FE-180?atlOrigin=eyJpIjoiNTJjYTg3MzZlNTk0NDIyODk0MmFkMmYyYTNjMDI5M2YiLCJwIjoiaiJ9)
When pushing translations from Phrase, the Pull request opened is not well linted. We need to format the file manually. 
Files have to be formated manually
Github action automatically format the files
[FE-180]: https://autoricardo.atlassian.net/browse/FE-180?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: lint locale files

- src/components/discreteSlider/index.tsx
- src/themes/components/slider.ts
JIRA Reference: [JIRA](https://smg-au.atlassian.net/browse/VSST-1786)
Design Reference: [Design](https://www.figma.com/file/MxJLYwGMJB5m1VDGgi8Lku/Private-insertion-flow?type=design&node-id=75-20572&mode=design&t=cMpN8ZzECCeX6drv-0)
Discrete slider label should be properly centered below slider thumb.
[Storybook - DiscreteSlider](https://discrete-slider-label-centered-components-pkg.branch.autoscout24.dev/?path=/docs/components-filter-discrete-slider--docs)
> fix: Discrete slider label centered

- .github/workflows/lint-i18n-files.yml
- .github/workflows/phrase-pr-notification.yml
[IN-1463](https://autoricardo.atlassian.net/browse/IN-1466?atlOrigin=eyJpIjoiNmZkNzBlZjM3ZmIzNDIxOGFhZWFhNDczYjE0MGY2MzUiLCJwIjoiaiJ9)
I wanted to improve the Github action that formats the i18n files from a Phrase branch. 
+ 
To merge Phrase generated PRs timely, we want to have a Slack channel which send an alert everytime a phrase-translations branch is created or updated.
If a phrase-translation branch is already open and new changes are done through Phrase, we have to close and reopen the PR to run the format.
If the files are already well linted (it happens in components-pkg), we try to commit nothing so it returns an error.
+
No Slack channel
If a phrase-translation branch is already open and new changes are done through Phrase, format:i18n is triggered automatically.
If the files …
> Phrase branch: improved Github actions

- src/components/discreteSlider/index.tsx
References:
[JIRA](https://smg-au.atlassian.net/browse/VSST-1786)
[Design](https://www.figma.com/file/MxJLYwGMJB5m1VDGgi8Lku/Private-insertion-flow?type=design&node-id=75-19614&mode=design&t=1oOm0ryuGQF86P0q-0)
DiscreteSlider mark label type should be changed from string to ReactNode. This way there can be versatile and custom implementation of label that depends on design requirement. (E.g.: On larger devices show text as label, but on smaller devices show an icon instead)
[Storybook - DiscreteSlider](https://discrete-slider-mark-label-type-components-pkg.branch.autoscout24.dev/?path=/story/components-filter-discrete-slider--overview)
> fix: DiscreteSlider mark label type

- src/components/checkboxFilter/index.tsx
[Ticket](https://smg-au.atlassian.net/browse/DM-2805)
Designers wanted smaller padding (in our case it's margin) for grouped checkboxes. Instead of having 12px top and bottom (in our case 24px margin bottom) we want that to be 8px bottom and top (so 16px margin bottom).
> fix: padding between checkbox filter group

- src/components/discreteSlider/__tests__/DiscreteSlider.Test.tsx
- src/components/discreteSlider/index.tsx
References
[JIRA](https://smg-au.atlassian.net/browse/VSST-2001)
[PR](https://github.com/smg-automotive/seller-web/pull/1475)
When applyIndentation is true, which is default value of that prop, moving thumb past the first option on DiscreteSlider causes unexpected state behaviour that lead to weird experience.
https://github.com/smg-automotive/components-pkg/assets/153915313/de6aba60-8373-43fa-9d75-690264ac89bf
https://github.com/smg-automotive/components-pkg/assets/153915313/7f204b7e-0513-4533-9b3b-916175d7917a
[Storybook - DiscreteSlider](https://discrete-slider-bug-fix-undefined-value-components-pkg.branch.autoscout24.dev/?path=/docs/components-filter-discrete-slider--docs)
> fix: Indentation on DiscreteSlider causes unexpected state behaviour

- src/components/popover/index.tsx
References [VSST-2072](https://smg-au.atlassian.net/browse/VSST-2072)
Renders popover in a portal with a popover specific popover `zIndex` in order to internalize overlay functionality. The implementation is similar to existing filter popover.
Need to add `zIndex` and `position` in places where popover is used.
Overlaying is handled internally.
https://render-popover-in-portal-components-pkg.branch.autoscout24.dev/?path=/story/components-overlay-popover--popover
> feat: render popover in portal

- src/components/rangeFilterInputWithSlider/index.stories.mdx
- src/components/rangeFilterInputWithSlider/index.tsx
- src/components/rangeSlider/RangeSliderWithChart.tsx
- src/components/rangeSlider/RangeSliderWithScale.tsx
References [DM-2826](https://smg-au.atlassian.net/browse/DM-2826)
Due to optimisation issue with histograms, we have decided to replace majority of histograms with range slider only.
This range slider need to have custom scale like we have for histograms.
Check here https://feat-range-slider-filters-listings-web.branch.autoscout24.dev/de/s
> feat: add range slider with custom scale

- src/components/checkboxFilter/CheckboxGroupCollapsibleWithChildren.tsx
- src/components/checkboxFilter/GroupedCheckboxFilterStoryTemplate.tsx
- src/components/filterPatterns/modal/index.stories.mdx
- src/components/filterPatterns/popover/index.stories.mdx
When the label was long, the chevron icon was no longer aligned with the facet
Aligned with the facet even if the label breaks on multiple lines
> fix: chevron alignment on grouped checkbox filter

- src/components/carousel/__tests__/Index.Test.tsx
References [JIRA](https://smg-au.atlassian.net/browse/FE-238)
Some ESLint configurations were set as global configs and respective lines for disabling them can be removed from the projects.
ESLint doesn't allow uppercase property names and double leading underscore.
ESLint allows uppercase property names and double leading underscore.
> chore: delete disabled eslint rule

- src/components/navigation/header/config/DrawerNodeItems.tsx
- src/locales/de/dict.json
- src/locales/en/dict.json
- src/locales/fr/dict.json
- src/locales/it/dict.json
References [DM-2877](https://smg-au.atlassian.net/browse/DM-2877)
Link is present in header
Link is not present in header
> fix: remove header drawer link

- src/components/navigation/header/config/headerLinks.ts
- src/components/navigation/header/index.stories.mdx
References https://smg-au.atlassian.net/browse/IN-1727
Changes the "Verkaufen" Link for professional sellers 
Link pointed to landingpage
Link points to insertion
https://lkappeler-in-1727-update-link-components-pkg.branch.autoscout24.dev/?path=/docs/patterns-navigation-header--docs
> Update "Verkaufen" link for professional sellers on autoscout24

- src/components/filterPatterns/popover/Popover.tsx
- src/components/filterPatterns/popover/index.tsx
[References [link the ticket here]](https://smg-au.atlassian.net/browse/DM-2891)
We had some white space at the end of the page. The paddingY="2xl" on popoverContent gives it. So we needed to only apply it when popover is open.
Check whether the white space is still present and that all filters are working as before.
> fix: remove paddingY from popover initial load

- src/components/filterPatterns/popover/index.stories.mdx
- src/components/filterPatterns/popover/index.tsx
- src/components/filterPatterns/popover/props.ts
[Ticket](https://smg-au.atlassian.net/browse/DM-2923)
Add optional prop to popover component so that height of the popover filter can be changed. This is due to different height sizes on homepage.
> fix: add height prop for popover filters

- src/components/radio/index.stories.mdx
- src/components/radio/index.tsx
- src/themes/components/radio.ts
- Adding font weight variant to input radio component.
- Introducing `md` size for input radio component.
https://zbiljic-extend-radio-label-components-pkg.branch.autoscout24.dev/?path=/docs/components-forms-radio--docs
- Check `size` prop - `sm` | `base` | `md`
- Check `fontRegular` & `fontBold` variants
> fix: extending radio label

- src/components/icons/CategoryAIcon.tsx
- src/components/icons/CategoryAMinusIcon.tsx
- src/components/icons/CategoryAOneIcon.tsx
- src/components/icons/VehicleTypesMotorcycleStarIcon.tsx
- src/components/icons/index.ts
References
[JIRA](https://smg-au.atlassian.net/browse/DM-2411)
[Design](https://www.figma.com/file/mitrdndvcCjzikpQiLwZxJ/AS24-Home-Design?type=design&node-id=1684-154150&mode=design&t=9J6onANcLn75fiRj-0)
Add missing icons for Search trends section links on Home page.
Missing icons: 
- VehicleTypesMotorcycleStarIcon
- CategoryAOneIcon
- CategoryAIcon
- CategoryAMinusIcon
Added icons: 
- VehicleTypesMotorcycleStarIcon
- CategoryAOneIcon
- CategoryAIcon
- CategoryAMinusIcon
Icons are optimized using svgo.
[Storybook - Icons](https://dm-3037-search-trend-icons-components-pkg.branch.autoscout24.dev/?path=/docs/foundations-icons--docs)
> feat: Add icons for Search trends section on Home page.

- src/components/navigation/header/index.tsx
References [JIRA](https://smg-au.atlassian.net/browse/IN-1749)
We were asked by UX Team to increase header left and right padding for desktop viewports (SM and above, >= 768px).
From 768px (SM) and above, header left and right padding is 16px.
From 768px (SM) and above, header left and right padding is 24px.
https://fix-header-padding-components-pkg.branch.autoscout24.dev/?path=/docs/patterns-navigation-header--docs
> fix: increase header padding from SM break-point and above

- src/components/alert/index.tsx
References [Previous PR](https://github.com/smg-automotive/components-pkg/pull/1008), [IN-1856](https://smg-au.atlassian.net/browse/IN-1856)
Link inside information box is centered on small screens so we want to change that and to keep previous behaviour with new functionality.
[Test branch](https://in-1820-ivi-information-alert-seller-web.branch.autoscout24.dev/de/insertion/identify?versionIdentificationMethod=certification-number)
> fix: remove prop to avoid centering link

- src/components/navigation/header/__tests__/index.Test.tsx
- src/components/navigation/header/config/DrawerNodeItems.tsx
- src/components/navigation/header/config/headerLinks.ts
- src/components/navigation/header/index.stories.tsx
- src/components/navigation/header/index.tsx
- src/types/tracking.ts
References https://smg-au.atlassian.net/browse/DM-3049
To measure the performance of the new EV hub, we add tracking to the main navigation items in the header to have a baseline.
FYI: as per Raluca, at the moment we only track the main items. The ones collapsed in drawers not.
No tracking
Tracking
> feat: add tracking to main header items

- src/themes/components/button.ts
- src/themes/components/input.ts
- src/themes/shared/typography.ts
References https://smg-au.atlassian.net/browse/FE-266
Input fields need to have at least a font-size of 16px Otherwise, browsers automatically zoom in when the input is focussed.
* I will address the radio and checkbox points separately becaussseeee they will cause breakingChanges in listings an seller projects.
* I checked with the UX-Designers  and we won't need the button-small token for future designs. 
Please check the fontSize is now 16px instead 14px in all the sizes on: inputs, select and button components
> fix: changed font size

- src/components/checkbox/index.tsx
- src/components/checkboxGroup/index.stories.tsx
- src/components/checkboxGroup/index.tsx
- src/components/radio/index.stories.tsx
- src/components/radio/index.tsx
- src/themes/components/checkbox.ts
- src/themes/components/radio.ts
References https://smg-au.atlassian.net/browse/DM-3111
After changing the fontSize on the input/select/button keeping only `16px` and removing the `14px` fontSize. We need to unify the sizes and remove the unnecessary ones for the radioButton and checkbox.
* I am checking with the UX-Designer why we have the `md` variation which is too huge `24px`. It doesn't have any sense to have it, we ONLY need the `16px`. In case that we don't need the variation `md` and be sure that we won't introduce it again, I will create a new PR for it.
* I check in seller and listings projects and we don't use the small variation for the radio button. Buuuut in any case I will do a breaking change to be sure that I don't break something
Please check:
* We only have two variations `base, md` and no more the …
> BREAKING CHANGE: removed small variation - radiobutton/checkbox

- src/components/navigation/header/NavigationItems.tsx
- src/components/navigation/header/index.tsx
References https://smg-au.atlassian.net/browse/DM-3131
1. go to SRP
2. change to french [Voitures - acheter un véhicule d'occasion | AutoScout24](https://www.autoscout24.ch/fr/s) 
3. click the logo in the header
→ you land on the german homepage
Test the same on https://talamcol-add-cache-srp-listings-web.branch.autoscout24.dev/fr
> fix: language in logo click on header

- src/components/checkboxFilter/CheckboxGroupCollapsibleWithChildren.tsx
References https://smg-au.atlassian.net/browse/DM-3110
The indent of the checkbox should align with the label of the parent
https://talamcol-group-indent-components-pkg.branch.autoscout24.dev/?path=/story/components-filter-checkbox--with-grouped-items
> fix: increase indentation for checkbox group

- src/components/alert/index.tsx
[IN-1884](https://smg-au.atlassian.net/browse/IN-1884?atlOrigin=eyJpIjoiZjhkYjQ5ZGY4MDk4NDA3ZGJiZjdkYWVhZjdjMWM0MzEiLCJwIjoiaiJ9)
While working on [this task](https://smg-au.atlassian.net/browse/IN-1820), we removed the `as=button` from the link in the Alert box component to fix a CSS issue, [here](https://github.com/smg-automotive/components-pkg/pull/1012). However, it’s not right for accessibility.
Link in the alert box is not marked as button
Link in the alert box is marked as button and text remains on the left even on small screens. 
The CSS issue was especially visible [in this PR](https://github.com/smg-automotive/seller-web/pull/1773), I extended the branch and opened a test one for you to check: https://in-1884-seller-web.branch.autoscout24.dev/de/insertion/identify?versionIdentif …
> fix: link alignment in Alert box

- src/components/alert/index.tsx
[Reference](https://github.com/smg-automotive/components-pkg/pull/1030#issuecomment-2107086952)
Following [this PR](https://github.com/smg-automotive/components-pkg/pull/1030), Nenad noticed that with `width="max-content"`,  the content of the whole page is zoomed out. 
It's not the case using
`display="inline-block" width="fit-content"`, so I went back to this. 
https://github.com/smg-automotive/components-pkg/assets/52455155/cc5cd3c8-b59e-4b59-aeb7-16bfbfc09059
https://github.com/smg-automotive/components-pkg/assets/52455155/4ab9d928-e4c0-4cab-98e5-55f0af7e13be
The CSS issue is visible in the IVI PR, I extended the branch and opened a test one for you to check: https://test-component-seller-web.branch.autoscout24.dev/de/insertion/identify?versionIdentificationMethod=certification-number& …
> fix: link in alert component

- src/components/checkboxFilter/CheckboxGroupCollapsibleWithChildren.tsx
- src/components/checkboxFilter/index.stories.tsx
- src/components/checkboxFilter/index.tsx
- src/components/checkboxFilter/type.ts
References https://smg-au.atlassian.net/browse/DM-3109
Since we have a search field on equipment and we need more horizontal space, it does not make sense to collapse the checkboxes in that case (for fuel type and others it still makes a lot of sense)
Therefore we add the possibility to have the checkboxes always expanded
https://talamcol-always-expand-equipment-listings-web.branch.autoscout24.dev/de/s/advanced
> feat: allow to have checkbox always expanded

- src/components/icons/CheckmarkCircleIcon.tsx
- src/components/icons/index.ts
References [VSST-2415](https://smg-au.atlassian.net/browse/VSST-2415)
The new icon is present in the private seller insertion flow success page.
The svg has been optimized via https://svgoptimizer.com/
No checkmark circle icon.
> feat: add checkmark circle icon

- src/components/tab/index.stories.tsx
- src/components/tab/index.tsx
- src/themes/components/tabs.ts
References  https://smg-au.atlassian.net/browse/ST-170 / parent https://smg-au.atlassian.net/browse/ST-67
We want to introduce new tab variation for cockpit page in order to display KPI performance.
n/a
https://fitted-tab-variant-components-pkg.branch.autoscout24.dev/?path=/docs/components-navigation-tabs--documentation
> feat: adding enclosed tab variant

- src/components/tab/index.stories.tsx
- src/themes/components/tabs.ts
References https://smg-au.atlassian.net/browse/ST-197
Removing double border & changing font color in order to improve contrast.
https://fix-enclosed-tab-variant-components-pkg.branch.autoscout24.dev/?path=/docs/components-navigation-tabs--documentation
> fix: tab enclosed variant border & font color

- src/components/input/index.stories.tsx
- src/components/input/index.tsx
- src/components/select/index.tsx
References [VSST-2481](https://smg-au.atlassian.net/browse/VSST-2481)
Added input field left addon prop.
This is required for profile page phone number input:
Left addon cannot be added to input field.
Left addon can be added to input field.
- https://input-left-addon-components-pkg.branch.autoscout24.dev/?path=/story/components-forms-input--with-left-addon-element-select
> feat: input left addon

- src/components/icons/CompareIcon.tsx
Allows me to overwrite the filled state with an animation 
https://talamcol-feat-add-comparison-tiem-listings-web.branch.autoscout24.dev/de/s
> fix: allow to set fill state on comparison icon

- src/components/alert/Bare.tsx
- src/components/alert/index.tsx
While working on some toasts and having to pass tracking to the link, I realized that the props are not forwarded
> feat: fix alert link and add possibility to pass NextLink

- src/components/popover/index.stories.tsx
- src/components/popover/index.tsx
- src/themes/components/index.ts
- src/themes/components/popover.ts
[ST-137](https://smg-au.atlassian.net/browse/ST-137?atlOrigin=eyJpIjoiZGEyMmNkNzllZmI5NDZkMjg1Y2RhMTg3MjZjNGNlYjkiLCJwIjoiaiJ9)
We need to use the popover to display KPI's metrics filters in the cockpit like the design below. 
To achieve that, we need additional props
n/a
New props: trigger, contentWidth, contentPadding, showArrow, closeOnBlur, gutter
> feat: extend popover component to fit the cockpit needs

- src/components/articleTeaser/index.tsx
- src/components/vehicleReference/index.stories.tsx
- src/components/vehicleReference/index.tsx
- src/themes/components/vehicleReference.ts
References https://smg-au.atlassian.net/browse/DM-3436
As per design, we can adjust this globally for all the pages
see here: https://github.com/smg-automotive/listings-web/pull/2489
> feat: adjust vehicle reference and article teaser to new success page layout

- src/components/navigation/header/config/DrawerNodeItems.tsx
- src/locales/de/dict.json
- src/locales/en/dict.json
- src/locales/fr/dict.json
- src/locales/it/dict.json
References [VSST-2512](https://smg-au.atlassian.net/browse/VSST-2512)
We need this link until we release private supply (on 15th of the August). After we release new insertion, VP, profile page for privates, we need to remove this link from header (we don't support shopping card anymore).
For professional, it can be removed now - (we forgot to remove when professional was released).
> Private INSERTION RELEASE - Fix: remove shoppingCard link for all users 

- src/components/navigation/footer/config/index.ts
- src/components/navigation/header/config/DrawerNodeItems.tsx
References https://smg-au.atlassian.net/browse/DM-3245
After the seller search page release, we can adjust the seller search page link with the new one on header and footer
Please check the header and footer
> fix: adjusted seller search link with new url

- src/components/navigation/header/config/DrawerNodeItems.tsx
References [ticket](https://smg-au.atlassian.net/browse/VSST-2517?atlOrigin=eyJpIjoiYTJkZTU2YmExZTkwNDhiM2IzNDk5ZjU3N2ZjMTU1MTciLCJwIjoiaiJ9)
Instead of legacy link to private profile /{language}/member/masterdata/addressedit replace with new link /{language}/profile in navigation headers
By hovering over the Link (Contact details) in the menu bar, it shows /{language}/member/masterdata/addressedit for private seller but redirects to /{language}/profile. Private and Professional sellers both shared the same Link.
By hovering over the Link now, it shows the right address /{language}/profile when using a private account and shows {language}/member/masterdata/addressedit when using a private account.
[deployment](https://replace-link-navigator-header-components-pkg.branch.autoscout24.dev)
> chore: Replaced private profile link in navigation header

- src/components/formControl/index.stories.tsx
- src/components/formControl/index.tsx
References:
- [IN-1793](https://smg-au.atlassian.net/browse/IN-1793)
- [Seller web PR](https://github.com/smg-automotive/seller-web/pull/2248)
We want to display label, tooltip and button in the same row.
n/a
https://in-1973-version-input-tooltip-components-pkg.branch.autoscout24.dev/?path=/story/components-forms-form-control--with-tooltip-and-button
[IN-1793]: https://smg-au.atlassian.net/browse/IN-1793?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: enable showing tooltip with the button

- src/themes/components/slider.ts
On last step of Discrete slider, if there is space in mark step label it breaks in two lines.
Overflow wrap set to break-word.
Apply white-space:nowrap.
[Storybook](https://fix-discreteslider-mark-components-pkg.branch.autoscout24.dev/?__cf_chl_tk=eGCB1WpVO.UJYn5YnAPMqWHfZkuNpOEjeTvPGVFrkEw-1725463612-0.0.1.1-6996)
> fix: Fix Discrete slider mark word break on space.

- src/components/navigation/header/config/DrawerNodeItems.tsx
- src/components/navigation/header/index.tsx
- src/types/entitlements.ts
[ST-372](https://smg-au.atlassian.net/browse/ST-372)
For the cockpit release to come, in case the user is part of beta testing group we show cockpit link and hide dealer dashboard link. If the user is not part of the beta group we hide cockpit link and show dealer dashboard. 
Cockpit was hidden for everyone
Dealer dashboard is visible for everyone
We show cockpit link and hide dealer dashboard link if the user is part of beta group 
If the user is not part of the beta group we hide cockpit link and show dealer dashboard. 
You can test seller web [here](https://st-372-seller-web.branch.autoscout24.dev/de) and listings [here](https://st-372-listings-web.branch.autoscout24.dev/de). 
Currently only user 60601 is part of the group, so if you login with this account, you will see the cockpit …
> feat: show and hide cockpit link

- src/components/modal/index.stories.tsx
- src/components/modal/index.tsx
- src/themes/components/modal.ts
- src/themes/shared/sizes.ts
- src/themes/shared/space.ts
References https://smg-au.atlassian.net/browse/SST-1010
We discussed with the UX team to align our pages to match the auth0 modals as they are limited in configuration options. Therefore we are going to add some auth0-specific tokens to our components package so we use them within the custom pages
n/A
auth0 specific tokens added and modal extended
Check the modal and token docs
> feat(tokens): Add auth0 sepecific tokens and allow them in modal

- src/components/flex/index.tsx
Revert this https://github.com/smg-automotive/components-pkg/pull/1152 because `gap` is not supported by all browsers
> fix: omit gap prop in flex component

- src/components/icons/DigitalContractIcon.tsx
References [VSST-2829](https://smg-au.atlassian.net/browse/VSST-2829)
We need to present a digital contract icon centered within a yellow circle. Currently, the icon is offset to the left so this PR aims to fix the alignment issue.
Check if the digital contract icon is aligned to center.
[VSST-2829]: https://smg-au.atlassian.net/browse/VSST-2829?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: align digital contract icon to center

- src/components/tab/index.stories.tsx
- src/components/tab/index.tsx
- src/themes/components/tabs.ts
References [VSST-2932](https://smg-au.atlassian.net/browse/VSST-2932)
The new professional seller profile page has full width tabs:
This PR adds a new `fullWidth` variant to the existing tabs component.
No full width variant of tabs component.
- https://full-width-tabs-components-pkg.branch.autoscout24.dev/?path=/docs/components-navigation-tabs--documentation#variant%20%3E%20full%20width
[VSST-2932]: https://smg-au.atlassian.net/browse/VSST-2932?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: full width tabs

- src/components/popover/index.tsx
Extending popover props in order to support new design for insights.
https://www.figma.com/design/JIg3a2e1WTSGRm0UBF9Hc5/Dealer-Dashboard-2024?node-id=5027-17427&node-type=frame&t=6x9ziUdmYGsfFAF5-0
> fix: extending popover props

- src/components/icons/MinusIcon.tsx
- src/components/icons/SparklingCarIcon.tsx
- src/components/icons/index.ts
Adding sparkling car and minus icons.
https://www.figma.com/design/JIg3a2e1WTSGRm0UBF9Hc5/Dealer-Dashboard-2024?node-id=5027-17427&node-type=frame&t=aBU4bj7AbfhjEHwN-0
https://sparkling-car-and-minus-icons-components-pkg.branch.autoscout24.dev/?path=/docs/foundations-icons--documentation
> feat: sparkling car & minus icons

- src/components/navigation/footer/config/index.ts
- src/components/navigation/header/config/DrawerNodeItems.tsx
References [VSST-3089](https://smg-au.atlassian.net/browse/VSST-3089)
- Go to: https://fix-link-sellers-search-listings-web.branch.autoscout24.dev/de
- Header: click on `suchen` and hover on `handler suchen` -> /sellers/search link should be visible 
- Footer: hover on `garagen und handler suchen` -> /sellers/search link should be visible 
[VSST-3089]: https://smg-au.atlassian.net/browse/VSST-3089?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: update link for sellers search

- src/components/navigation/header/config/DrawerNodeItems.tsx
- src/locales/de/dict.json
- src/locales/en/dict.json
- src/locales/fr/dict.json
- src/locales/it/dict.json
References:
- [IN-2432](https://smg-au.atlassian.net/browse/IN-2432)
- seller-web [PR](https://github.com/smg-automotive/seller-web/pull/2752)
We want to remove old Vehicle Pool link from user menu.
- Start the project
- Open Navigation -> Header -> Professional
- Old link doesn't exist in user menu (check languages)
[IN-2432]: https://smg-au.atlassian.net/browse/IN-2432?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: remove old vehicle pool link from user menu

- src/components/icons/DownloadIcon.tsx
- src/components/icons/index.ts
Adding download icon.
https://adding-download-icon-components-pkg.branch.autoscout24.dev/?path=/docs/foundations-icons--documentation
> fix: adding download icon

- src/components/rating/index.tsx
References [JIRA](https://smg-au.atlassian.net/browse/DM-3655)
To bring more color and align as well with Google rating stars we want to change the colors of the stars from #gray-900 to #orange-300
Once PR is merged and version is bumped on dependent projects, make sure that rating stars color is changed.
> fix: change rating stars color

- src/components/icons/SwissFlagIcon.tsx
- src/components/icons/index.ts
https://smg-au.atlassian.net/jira/software/projects/ST/boards/1109?assignee=712020%3A7b8fcbea-c829-48f9-ac8e-a01a9c310984&selectedIssue=ST-689
We are currently building new OptimizerPro page on Seller web project and we need Swiss flag icon for one of the components in it.
We did not have Swiss flag icon component.
I have added Swiss flag icon component.
> feat: Swiss flag icon added

- src/themes/components/tabs.ts
References [VSST-3240](https://smg-au.atlassian.net/browse/VSST-3240)
The new professional seller info management page information section renders tab panels without any margin. Since the `fullWidth` variant is only used for the professional seller profile page (where we stack margin + padding to achieve the final spacing), I've opted into removing the margin from the variant which will:
1. allow implementing info management page according to design
2. simplify profile page spacing implementation
[VSST-3240]: https://smg-au.atlassian.net/browse/VSST-3240?atlOrigin=eyJpIjoiNWRkN …
> feat: remove full width tab panel margin

- .storybook/main.ts
Correctly maps static dirs to host static assets and fonts in storybook
> chore: fix fonts hosting in storybook

- src/components/navigation/footer/config/index.ts
- src/locales/de/dict.json
- src/locales/en/dict.json
- src/locales/fr/dict.json
- src/locales/it/dict.json
[ST-760](https://smg-au.atlassian.net/browse/ST-760?atlOrigin=eyJpIjoiMDU0N2QwMzE2NTZlNDkzY2E5NzRjYTc3MDcxMWY4ZDciLCJwIjoiaiJ9)
We would like that dealers who are not yet working with us can find information about working with us. Therefore a link to the professional abos should be visible in the footer
[ST-760]: https://smg-au.atlassian.net/browse/ST-760?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: add professional packages link in footer

- src/themes/components/menu.ts
References [VSST-3226](https://smg-au.atlassian.net/browse/VSST-3226)
Due to no width constraint of the menu content, it was possible for menu to grow beyond the width of the screen (eg. when a menu item text was wider than the page), resulting in the page layout being broken - it was possible to horizontally scroll the page as seen in the ticket.
Page layout broken and is horizontally scrollable.
Page layout is not broken and is not horizontally scrollable.
- https://fix-320px-layout-overflow-seller-web.branch.autoscout24.dev/fr/features/top-list/manage
- https://fix-320px-layout-overflow-seller-web.branch.autoscout24.dev/fr/features/top-vehicle/manage
- https://fix-320px-layout-overflow-seller-web.branch.autoscout24.dev/fr/vehicle-management
- login with a professional seller
- visit …
> feat: constrain menu content max width

- src/components/navigation/header/config/hci.ts
[DM-3564](https://smg-au.atlassian.net/browse/DM-3564)
We already have rewrite worker for '/hci-management' implemented in [terraform-cloudflare](https://github.com/smg-automotive/terraform-cloudflare/blob/ff48c96555c65098349566d61d4397fd7703a104/workers/rewrite-hci-management/src/rewrite-hci-management.ts#L4), and also [redirect](https://github.com/smg-automotive/terraform-cloudflare/blob/ff48c96555c65098349566d61d4397fd7703a104/workers/redirect-hci-management/src/redirect-hci-management.ts) from old url ('member/hci') to the new one. We can keep it for now, because there might be bookmarks in users browsers pointing to the old url.
HCI link ('member/hci')  redirects to new HCI Seller Page route in seller-web ('/hci-management/')
HCI link pointing directly to '/hci-management'
[DM-3564]: …
> fix: update HCI link in navigation header

- src/components/navigation/header/config/Presence.tsx
References [VSST-3624](https://smg-au.atlassian.net/browse/VSST-3624)
Updated header info management link
old link -> [cloudflare redirect](https://github.com/smg-automotive/terraform-cloudflare/tree/8cd7f04451f0cee7729b19d2174d0c5f1a1ed082/workers/redirect-legacy-dealer-admin-page) -> new link
new link
- https://update-header-info-management-link-components-pkg.branch.autoscout24.dev/?path=/docs/patterns-navigation-header--documentation#professional
- ensure the `InfoPage` header link (under profile drawer) matches cloudflare redirect worker behaviour
[VSST-3624]: https://smg-au.atlassian.net/browse/VSST-3624?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: update header info management link

- src/components/navigation/header/config/Optimizer.tsx
[ST-1065](https://smg-au.atlassian.net/browse/ST-1065)
Replace optimizer legacy link with the vehicle pool one (we need a query param to display a banner explaining why we land here)
[ST-1065]: https://smg-au.atlassian.net/browse/ST-1065?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: change optimizer link in header

- src/components/colorPicker/__tests__/ColorPicker.Test.tsx
- src/components/colorPicker/index.stories.tsx
- src/components/colorPicker/index.tsx
- src/components/index.ts
References https://smg-au.atlassian.net/browse/VSST-3657
We needed a color picker input on the Create Photobar form in the Seller Info Management page.
Since no such component existed in the design system, this PR introduces a minimal, reusable ColorPicker component as a first version — implemented as a wrapper around the native .
It was not implemented.
> feat: implement color picker component

- src/components/icons/QualitySealIcon.tsx
- src/components/icons/index.ts
References [VSST-3643](https://smg-au.atlassian.net/browse/VSST-3643)
Added quality seal icon which will be used for the info management quali logo page. [Figma link](https://www.figma.com/design/BuUwTfOIJrE5oGiSDd8tf9/Professional-Management-Tool---Info-Page?node-id=4143-74083&t=CemmmifTy8eN5EQS-0)
No quality seal icon.
- https://quality-seal-icon-components-pkg.branch.autoscout24.dev/?path=/docs/foundations-icons--documentation
[VSST-3643]: https://smg-au.atlassian.net/browse/VSST-3643?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: quality seal icon

- src/components/navigation/header/__tests__/index.Test.tsx
- src/components/navigation/header/config/assure.ts
Reference: [DM-4455](https://smg-au.atlassian.net/browse/DM-4455) [DM-4480](https://smg-au.atlassian.net/browse/DM-4480)
We need to change the url for "Assure" in the Header navigation.
"Assure" link leads to legacy page on `/autoversicherung `path.
"Assure" link leads to the FinanceScout URLs listed in the [ticket](https://smg-au.atlassian.net/browse/DM-4455) description.
Check if the "Assure" link in Header points to the correct FinanceScout URLs.
[DM-4455]: https://smg-au.atlassian.net/browse/DM-4455?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DM-4480]: https://smg-au.atlassian.net/browse/DM-4480?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: change Assure link href in Header

- src/components/popover/index.tsx
[ST-1149](https://smg-au.atlassian.net/browse/ST-1149)
We have a white space at the bottom of the Optimizer page.
This is due to the Popover having 'relative' as position. Combined with the use of Portal and `w="full" h="full"`, we have this overlay at the bottom 
You can test seller web here: https://st-1149-bug-seller-web.branch.autoscout24.dev/de/optimizer/11321654
I tested that all Popover still works as usual. Same with listings-web
Thank you 
[ST-1149]: https://smg-au.atlassian.net/browse/ST-1149?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: popover white space

- src/components/navigation/header/config/DrawerNodeItems.tsx
- src/components/navigation/header/config/user.ts
References https://smg-au.atlassian.net/browse/FED-762
We discovered that private users are still accessing the MCV page for setting their language preference. This change aligns the link to the replattformed page thats already in place for professional users
> feat: Align lanauge settings

- src/components/navigation/footer/config/index.ts
- src/components/navigation/footer/index.tsx
References [PS-628](https://smg-au.atlassian.net/browse/PS-628)
There is no need to keep the featureFlag c2b in splitIO and code. 100% users sees the c2b.
Feature flag is in the code.
Feature flag is removed from the code.
Merging this in branch 23.x.
[PS-628]: https://smg-au.atlassian.net/browse/PS-628?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: remove c2b feature flag

- src/components/navigation/header/config/Presence.tsx
References https://smg-au.atlassian.net/browse/VSST-3728 https://smg-au.atlassian.net/browse/VSST-3630
Will check with Bojana do we need bucket icon in case seller does not have business image feature.
As far as I remember an idea is to have only one link related to seller management in future (e.g. seller management) instead of current info page, business image, photobar, working hours, etc. 
> fix: seller management links

- src/components/navigation/header/config/estimate.ts
[ST-1207](https://smg-au.atlassian.net/browse/ST-1207)
We released the new price estimate page, we can then change the link
Legacy link
New one 
[ST-1207]: https://smg-au.atlassian.net/browse/ST-1207?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: price estimator link

- src/components/navigation/header/__tests__/index.Test.tsx
- src/components/navigation/header/index.stories.tsx
- src/components/navigation/header/index.tsx
References https://smg-au.atlassian.net/browse/FED-781
Adds a boolean prop to conditionally hide the tenant selection menu in the project. It's a temporary fix until we develop a mechanism to synchronise selected tenant between the projects
> fix(temp): Conditionally hide tenant selection header menu

- src/components/navigation/header/drawer/index.tsx
- src/components/navigation/header/drawer/userInfo/index.tsx
- src/components/navigation/header/index.tsx
References: QA feedback
Tenant selection in listings web is still visible on mobile
> fix: hide mobile tenant selection

- src/components/icons/BookmarkIcon.tsx
Change in size of bookmark icon.
- Bookmark icon still renders correctly.
> fix: Bookmark icon size and path fix.

- src/components/navigation/header/FavoritesItem.tsx
- src/components/navigation/header/__tests__/index.Test.tsx
- src/components/navigation/header/config/DrawerNodeItems.tsx
- src/components/navigation/header/config/iconItems.ts
- src/components/navigation/header/config/user.ts
- src/components/navigation/header/index.tsx
Reference: [DM-4669](https://smg-au.atlassian.net/browse/DM-4669)
Add favorites link icon inside the navigation header (only for logged in user).
Test listings-web and seller-web with [this prerelease](https://www.npmjs.com/package/@smg-automotive/components/v/24.9.0-DM-4669-add-favorites-to-nav-header-5987f86e1bf03adca55ca6260941a1e87aea9d71.1).
[DM-4669]: https://smg-au.atlassian.net/browse/DM-4669?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add favorites link icon to navigation header

- src/themes/components/modal.ts
References [Tiecket](https://smg-au.atlassian.net/browse/VSST-3879?atlOrigin=eyJpIjoiNTM5OWU1YmYwM2U1NGJhMzk5YWNhNmZiOWJmNTA2YzgiLCJwIjoiaiJ9)
The modal on mobile view should be full page, with no margins at the top.
Modal variant 'topScroll' is not aligned with design, mobile version needs changes
TopScoll variant, has now no topPadding for mobile version
Got to the following link and choose as variant 'topScroll'
[deployment](https://removing-toppadding-mobile-modal-components-pkg.branch.autoscout24.dev/?path=/docs/components-data-display-modal--documentation)
> fix: remove paddingTop for small devices
