smg-automotive/components-pkg

src/theme/as24/index.ts, src/theme/ms24/index.ts, src/theme/shared/borderRadius.ts, src/theme/shared/index.ts, src/theme/stories/borderRadiusShowcase.tsx, src/theme/stories/theme.stories.mdx
References:
> Jira https://autoricardo.atlassian.net/browse/DM-169
> Figma https://www.figma.com/file/WmNmJ7jdB0Z7tOjj516nFB/AS24-Tokens?node-id=33%3A45
> Figma tokens https://github.com/smg-automotive/figma-tokens/blob/main/tokens.json
Setup of base themeBORDER RADIUS tokens as defined in the design system.
We added a new value for the border radius `none: 0`. Sergiu already added it in the figma-tokens and figma. So, everything is in sync now.
No base theme for the border radius tokens
Base theme for border radius tokens 🔘
=> feat: added border radius tokens

.storybook/preview.js
Reference: https://storybook.js.org/docs/react/essentials/viewport
Configure the storybook plugin to support our breakpoints
Default storybook breakpoints
OUR theme breakpoints
Please check that ONLY our theme breakpoints are displayed in the viewport toolbar.
=> chore: added viewport configuration

src/components/button/__tests__/Button.Test.tsx, src/components/formControl/__tests__/FormControl.Test.tsx, src/components/formControl/index.stories.mdx, src/components/formControl/index.tsx, src/components/input/__tests__/Input.Test.tsx, src/components/input/index.stories.mdx, src/components/input/size.stories.mdx, src/components/input/state.stories.mdx, src/components/link/__tests__/Link.Test.tsx, src/themes/components/form.ts, src/themes/components/formError.ts, src/themes/components/formLabel.ts, src/themes/components/index.ts, src/themes/shared/typography.ts
References https://autoricardo.atlassian.net/browse/DM-167
Adds form control component
No form control
Habemus form control:
Running storybook locally is required due to missing domain for branch deployment
=> feat: form control component

.storybook/main.js, helm-chart/branch.values.yaml, helm-chart/templates/ingress.yaml, public/robots.txt
Makes sure that branch deployments are not indexed in google.
=> Noindex nofollow

README.md
=> chore: added branch deployment link in README

src/components/simpleHeader/index.tsx, src/themes/components/simpleHeader.ts
Addressing Muchacho feedback 🧸 
https://github.com/smg-automotive/components-pkg/pull/149
=> fix: review-L

package-lock.json, package.json, rollup.config.js, src/components/vehicleReference/index.tsx, src/lib/index.ts, src/lib/lazy.ts, tsconfig.build_cli.json
Make sure that components package is treeshakeable so that we don't pull the entire chakra ecosystem
=> fix: treeshaking

README.md
=> chore: rename main branch in README

src/components/divider/index.stories.mdx, src/components/divider/index.tsx, src/components/index.ts, src/themes/components/divider.ts, src/themes/components/index.ts
References https://www.figma.com/file/OJYTePwDygrbpGG7s6G4Oi/Report-suspicious-request%2Fadvertisement?node-id=17%3A28419
Add the divider component
Please check the divider co,ponent
=> feat: added divider component

.storybook/preview.js, src/themes/stories/theme.stories.mdx
References https://autoricardo.atlassian.net/browse/FE-66
see: https://github.com/smg-automotive/components-pkg/pull/172/files#r947578360
Color rendering was broken in theme section
=> fix: colour palett rendering

src/components/layout/SingleColumnCentered.stories.mdx
=> chore: fix typo

src/index.ts
References N/A
export the useTheme hook from chakra so it can be used within the projects
Example use case https://github.com/smg-automotive/seller-web/pull/5/files#diff-44a1bc20f886945616b494ff9dcc3b2c224472e52f5a00eb83044357ee5969daR23
=> export use theme form chakra

src/components/badge/index.stories.mdx, src/components/badge/index.tsx, src/components/index.ts, src/themes/components/badge.ts, src/themes/components/index.ts, src/themes/shared/space.ts
References https://autoricardo.atlassian.net/browse/VSST-407
Adds a badge component
Adapts spacing as needed
http://localhost:6006/?path=/docs/data-display-badge--overview
=> feat(Badge): Add Badge component

src/components/index.ts, src/components/menu/index.stories.mdx, src/components/menu/index.tsx, src/themes/components/index.ts, src/themes/components/menu.ts
References https://autoricardo.atlassian.net/browse/VSST-412
Design: https://www.figma.com/file/8vy6tgk0DV9KSKyJBjiLSH/12.-AS24---Web---Patterns
Adds the Menu component
N/A
http://localhost:6006/?path=/story/patterns-data-display-menu--overview&args=title:Hello
=> feat(Menu): Add Menu component

src/components/icons/CheckmarkIcon.tsx, src/components/icons/index.ts
https://autoricardo.atlassian.net/browse/VSST-413
Add Checkmark icon as part of stepper component for insertion
No checkmark icon
=> feat: add checkmark icon

src/components/alert/index.stories.mdx, src/components/alert/state.stories.mdx, src/components/articleTeaser/index.stories.mdx, src/components/badge/index.stories.mdx, src/components/box/index.stories.mdx, src/components/button/index.stories.mdx, src/components/checkbox/index.stories.mdx, src/components/datePicker/index.stories.mdx, src/components/divider/index.stories.mdx, src/components/formControl/index.stories.mdx, src/components/formLabel/index.stories.mdx, src/components/heading/index.stories.mdx, src/components/input/index.stories.mdx, src/components/input/size.stories.mdx, src/components/input/state.stories.mdx, src/components/link/index.stories.mdx, src/components/list/index.stories.mdx, src/components/radio/index.stories.mdx, src/components/radio/size.stories.mdx, src/components/radio/state.stories.mdx, src/components/select/index.stories.mdx, src/components/simpleHeader/index.stories.mdx, src/components/switchComponent/index.stories.mdx, src/components/text/index.stories.mdx, src/components/textarea/index.stories.mdx
References 
Slack discussion: https://automotivesmg.slack.com/archives/C03GK939L3V/p1665476814092119
To have a more understandable structure and a better visualisation in our components categories. In addition to having a synchronisation between figma and storybook structures.
Please take a look between the figma files and the storybook structure and let me know if you have another suggestion/idea/disagreement.
=> feat: structure storybook

src/components/icons/ArrowDownIcon.tsx, src/components/icons/ArrowUpIcon.tsx, src/components/icons/index.ts
References https://github.com/smg-automotive/listings-web/pull/192
Needed for the new expandable component in listings-web: https://github.com/smg-automotive/listings-web/pull/192
-
-
https://talamcol-expandable.components-pkg.branch.autoscout24.ch/?path=/story/foundations-icons--overview
=> feat: add new arrow icons

src/components/alert/index.stories.mdx, src/components/aspectRatio/index.stories.mdx, src/components/badge/index.stories.mdx, src/components/box/index.stories.mdx, src/components/breadcrumbs/index.stories.mdx, src/components/button/index.stories.mdx, src/components/center/index.stories.mdx, src/components/datePicker/index.stories.mdx, src/components/devOverlay/index.stories.mdx, src/components/divider/index.stories.mdx, src/components/energyLabel/index.stories.mdx, src/components/formLabel/index.stories.mdx, src/components/fullHeight/index.stories.mdx, src/components/grid/index.stories.mdx, src/components/icons/index.stories.mdx, src/components/layout/BaseGrid.stories.mdx, src/components/list/index.stories.mdx, src/components/menu/index.stories.mdx, src/components/missingImage/index.stories.mdx, src/components/mobileOnlyAccordion/index.stories.mdx, src/components/radio/RadioList.stories.mdx, src/components/select/index.stories.mdx, src/components/simpleHeader/index.stories.mdx, src/components/spinner/index.stories.mdx, src/components/switchComponent/index.stories.mdx, src/components/text/index.stories.mdx, src/components/tooltip/index.stories.mdx
References  https://github.com/smg-automotive/components-pkg/pull/321#issuecomment-1308857463
Make storybook easier to use while going through the tree for finding a component. Besides some small clean up regarding the stories were done .
All the stories work as before.
=> chore: adjusted stories tree

src/components/button/index.stories.mdx, src/components/button/index.tsx, src/themes/components/button.ts
References https://autoricardo.atlassian.net/browse/DM-727
Primary and Secondary buttons with icon
No icons on the button component 🧟‍♀️
Icons on the button component 🙌🏼
Please check the new button variations (left and right button).
=> feat: added icon on button

src/components/icons/ShareIcon.tsx, src/components/icons/index.ts
Adding the share icon for the new PDP
=> feat: share icon

package-lock.json, package.json, src/components/devOverlay/__tests__/DevOverlay.Test.tsx, src/components/devOverlay/index.stories.mdx, src/components/devOverlay/index.tsx, src/components/footer/config/__tests__/index.Test.ts, src/components/switchComponent/index.tsx, src/types/brand.ts
Reverts smg-automotive/components-pkg#364
=> Revert "fix: active theme"

src/components/pagination/__tests__/Pagination.Test.tsx, src/components/pagination/index.stories.mdx, src/components/pagination/index.tsx
Add workaround for Pagination API as it starts from 0.
Pagination starts from 1
Pagination starts from 0
https://yeavboi-pagination-fix.components-pkg.branch.autoscout24.ch/?path=/story/patterns-navigation-pagination--pagination
=> fix(pagination): starts from 0

src/components/formControl/index.stories.mdx, src/components/formControl/index.tsx, src/components/tooltip/index.stories.mdx, src/components/tooltip/index.tsx
https://autoricardo.atlassian.net/browse/VSST-849
Extend FormControl with a tooltip
N/A
https://boyarskiy-vsst-849.components-pkg.branch.autoscout24.dev/?path=/story/components-forms-form-control--with-tooltip
=> feat: add tooltip to the FormControl

README.md
=> chore: adjusted branch deployment link

README.md
=> chore: adjusted branch deployment convention

src/components/footer/Copyright.tsx
https://autoricardo.atlassian.net/browse/VSST-763
Copyright styles adjustments
=> fix(footer): adjust copyright styles

src/components/tab/__tests__/Tabs.Test.tsx, src/themes/components/tabs.ts
[This PR](https://github.com/smg-automotive/components-pkg/pull/430) was merged too quickly.
Here I adjust it according to the comments I missed.
=> fix: token and test

src/components/checkboxGroup/index.tsx
Adding explicit props to `CheckboxGroup` component.
Spreading props
=> fix: checkbox grp props

src/components/accordion/AccordionIcon.tsx, src/components/hooks/index.ts, src/components/hooks/useAccordionItemState.ts, src/components/index.ts
References https://autoricardo.atlassian.net/browse/DM-1050
Fixed the issue of accordion icon facing the wrong way on show/collapsed
Exposed accordion item state to have easy access to it
=> feat: expose accordion state

package-lock.json, package.json, src/components/accordion/__tests__/Accordion.Test.tsx, src/components/carousel/__tests__/Index.Test.tsx, src/components/carousel/__tests__/ThumbnailPagination.Test.tsx, src/components/checkbox/__tests__/Checkbox.Test.tsx, src/components/checkboxFilter/__tests__/Checkbox.Test.tsx, src/components/formControl/__tests__/FormControl.Test.tsx, src/components/input/__tests__/Input.Test.tsx, src/components/popoverFilter/__tests__/Index.Test.tsx, src/components/radio/__tests__/Radio.Test.tsx, src/components/tab/__tests__/Tabs.Test.tsx
References [link](https://autoricardo.atlassian.net/browse/DM-1247)
We have recently updated listing-web version of @testing-library/react to 14.0.0
With the update, we are getting `not wrapped in act(...)` warning when tests are running.
Having that in mind, I have updated version of testing-library and fixed all warnings.
Check https://app.circleci.com/pipelines/github/smg-automotive/components-pkg/3495/workflows/e451f182-63b6-4045-bced-e50cdf37d9a6/jobs/16437 - should be without warnings.
=> Update testing library

src/components/button/Button.TypeTest.tsx, src/components/button/index.stories.mdx, src/components/button/index.tsx
References https://autoricardo.atlassian.net/browse/DM-1304
Support NextLink in the component link button
Listings project -> https://github.com/smg-automotive/listings-web/pull/618
=> fix: adjusted button link

src/locales/de/dict.json
Exported the most recent locale files from Phrase
=> Updated translations from Phrase

src/components/index.ts
=> feat: export range filter component

src/components/icons/CalculatorIcon.tsx, src/components/icons/index.ts
References
> Jira ticket https://autoricardo.atlassian.net/browse/DM-1384
> Figma https://www.figma.com/file/QYphttx4oaLD2Sd2L50meg/AS24-Detail?node-id=4177-166053&t=00WFItat1UxGDVZZ-0
Add the calculator icon for the leasing rate implementation
Please check the icon is added
=> fix: added calculator icon

src/components/link/index.tsx
=> fix: link color

src/components/modal/index.tsx
Add motionPreset property to be able to disable modal animation.
N/A
motionPreset prop avaliable
-
=> fix(modal): add motionPreset prop

src/components/icons/PlusIcon.tsx, src/components/icons/index.ts, src/components/modal/index.tsx
References https://autoricardo.atlassian.net/browse/IN-680
Adds the plus icon
=> feat(Plus icon): Add new icon

src/components/popoverFilter/Popover.tsx
References https://autoricardo.atlassian.net/browse/DM-1474
Chakra has an issue with popover that zIndex is not working. https://github.com/chakra-ui/chakra-ui/issues/3043
=> fix: increase zIndex of popover

src/components/absoluteCenter/index.stories.mdx, src/components/absoluteCenter/index.tsx, src/components/index.ts
Add AbsoluteCenter component so we can Skip using Box ot other component when we need element that is absolute centered.
No absolute center component
With absolute center comp
=> feat: add AbsoluteCenter component

src/components/input/index.stories.mdx, src/components/input/index.tsx
Add a `password` type for the input component.
n/a
password type added
=> fix: input password type

src/components/navigation/header/NavigationAvatar.tsx, src/components/navigation/header/__tests__/index.Test.tsx, src/components/navigation/header/config/HeaderNavigationConfig.tsx, src/components/navigation/header/config/drawerNodeItems.ts, src/components/navigation/header/index.stories.mdx, src/components/navigation/header/index.tsx, src/components/navigation/header/links/NavigationLink.tsx
References https://autoricardo.atlassian.net/browse/VSST-1219
In order to support login and logout on multiple environments and projects we have to intruduce `onLogin` and `onLogout` callback
=> fix: adding login/logout callbacks

src/components/index.ts
Exporting navigation `UserType`
=> fix: export navigation user type

src/components/navigation/header/index.tsx
=> fix: close navigation drawer on logout

src/components/divider/index.tsx
References
Slack discussion: https://automotivesmg.slack.com/archives/C034EGP8GG0/p1680175774281809
I will go through all the components we have so far and give the flexibility to taking all the style props that the component offers BUT taking into consideration the DS, in some components we must restrict some props styles.
Note:  I need the divider component and some style props for the advanced search layout ticket.
After I merge this change I will make a clean up in all the projects, removing the extra wrappers we added, making the DOM cleaner. Wait for the PRs...
Note: this is not a breaking change.
The text component picked some style props
The text component takes all the style props without any restriction.
=> fix: extended divider component

src/components/navigation/header/drawer/index.tsx, src/components/navigation/header/index.tsx
After discussion with design team, decision is to make header take full width
N/A
Full width header
=> fix: full width header

src/components/navigation/footer/Link.tsx, src/themes/components/link.ts
References https://autoricardo.atlassian.net/browse/IN-963
Do not hide the link by making it the same color as the background
https://github.com/smg-automotive/components-pkg/assets/3371760/0ba6a2c8-af33-441f-a984-c0f537f21e11
https://github.com/smg-automotive/components-pkg/assets/3371760/1b89505d-d726-4af3-a259-bb28b315cc96
=> fix: keep link visible by color on click

src/components/index.ts, src/components/layout/WithVehicleReference.stories.mdx, src/components/rating/index.stories.mdx, src/components/rating/index.tsx
References https://autoricardo.atlassian.net/browse/DM-1596
To show the rating of the dealer on the PDP, we create a rating component. 
No rating component
Rating component
https://talamcol-rating-components-pkg.branch.autoscout24.dev/?path=/docs/components-data-display-rating--docs
=> feat: rating

src/components/button/index.tsx
References
Slack discussion: https://automotivesmg.slack.com/archives/C034EGP8GG0/p1680175774281809
I will go through all the components we have so far and give the flexibility to taking all the style props that the component offers BUT taking into consideration the DS, in some components we must restrict some props styles.
After I merge this change I will make a clean up in all the projects, removing the extra wrappers we added, making the DOM cleaner. Wait for the PRs...
Note: this is not a breaking change.
The button component omit some style props
The button component takes most of the style props with some committed styles.
=> fix: adjusted style props

src/themes/components/pagination.ts
References https://www.notion.so/smgnet/Add-space-between-pagination-buttons-11de75520d8a459b9652c3455a1b6468
Check that in the pagination buttons have a space between them
=> fix: added margin between buttons - pagination

src/components/rating/index.tsx
=> fix: using kebab-case for css properties in objects is not supported

src/components/icons/SortIcon.tsx, src/components/icons/index.ts
For sorting menu we need sort icon.
=> feat: add sort icon

src/components/index.ts, src/components/navigation/header/NavigationAvatar.tsx, src/components/navigation/header/NavigationItems.tsx, src/components/navigation/header/__tests__/index.Test.tsx, src/components/navigation/header/config/HeaderNavigationConfig.tsx, src/components/navigation/header/config/drawerNodeItems.ts, src/components/navigation/header/config/headerLinks.ts, src/components/navigation/header/config/headerNavigationLink.ts, src/components/navigation/header/index.tsx, src/components/navigation/header/types.ts, src/components/navigation/link.ts
References https://autoricardo.atlassian.net/browse/VSST-1315
Fixing header navigation links
Some of the links are not working and not linking to correct pages
Links are working as expected
=> fix: fixing header navigation links

src/components/navigation/header/config/drawerNodeItems.ts, src/locales/de/dict.json, src/locales/en/dict.json, src/locales/fr/dict.json, src/locales/it/dict.json
=> fix: remove unused link

src/components/navigation/header/config/drawerNodeItems.ts
Hidding dynamic links
N/A
No dynamic links, are links are hardcoded.
=> fix: remove dynamic links

src/components/navigation/header/config/drawerNodeItems.ts, src/components/navigation/header/config/headerLinks.ts
=> fix: estimate link

.eslintrc.js, package-lock.json, package.json, src/components/navigation/footer/config/factory.ts, src/components/navigation/header/config/HeaderNavigationConfig.tsx, src/components/navigation/link.ts, src/themes/components/drawer.ts, src/themes/components/vehicleReference.ts
References [DM-1705](https://autoricardo.atlassian.net/browse/DM-1705)
The [eslint-plugin-sonarjs](https://github.com/SonarSource/eslint-plugin-sonarjs) package provides additional rules based on SonarQube platform for detecting and preventing common coding issues.
It could help us to identify potential security vulnerabilities, performance bottlenecks, and logical bugs in code.
Check https://github.com/smg-automotive/au-docs/discussions/57
[DM-1705]: https://autoricardo.atlassian.net/browse/DM-1705?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViL …
=> feat: add sonar-js package

src/components/rangeFilterInputWithSlider/index.stories.mdx
Update stories to be more readable for consumers
=> chore: update filter range slider stories

src/components/icons/PenIcon.tsx, src/components/icons/index.ts
Needed for an edit functionality on the filters
=> feat: add pen icon

src/components/checkbox/index.tsx
Adding readonly prop to checkbox component
N/A
=> feat: adding readonly prop to checkbox

src/components/icons/CopyIcon.tsx, src/components/icons/index.ts
References https://autoricardo.atlassian.net/browse/DM-2026
=> feat: added copy icon

src/components/modal/index.tsx
Move action button to start position instead of end
=> fix: modal footer action button display

src/components/errorPage/index.stories.mdx, src/components/errorPage/index.tsx, src/locales/de/dict.json, src/locales/en/dict.json, src/locales/fr/dict.json, src/locales/it/dict.json, src/types/errorStatusCode.ts
So that we can render a different error page
=> feat: client side error page

src/components/pagination/index.tsx
Change pagination label to start from 1
=> fix: pagination label

src/components/navigation/BaseConfig.tsx, src/components/navigation/header/config/DrawerNodeItems.tsx, src/components/navigation/header/config/HeaderNavigationConfig.tsx, src/components/navigation/header/config/headerLinks.ts, src/components/navigation/header/config/headerNavigationLink.ts, src/components/navigation/link.ts
Reverts smg-automotive/components-pkg#731
=> fix: revert link fix for now to not block components update

src/components/navigation/BaseConfig.tsx, src/components/navigation/header/config/DrawerNodeItems.tsx, src/components/navigation/header/config/HeaderNavigationConfig.tsx, src/components/navigation/header/config/headerLinks.ts, src/components/navigation/header/config/headerNavigationLink.ts, src/components/navigation/link.ts
Dupplicate for this one: https://github.com/smg-automotive/components-pkg/pull/731 that was reverted
=> fix: internal link

src/locales/en/dict.json
I noticed a missing translation in English
=> chore: add missing translation

src/components/navigation/header/config/HeaderNavigationConfig.tsx, src/components/navigation/link.ts
Quick fix for https://app.datadoghq.com/logs?query=status%3Aerror%20kube_namespace%3Aprod%20service%3A%2A-web&agg_m=count&agg_q=service&agg_t=count&cols=host%2Cservice&index=main&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=desc&viz=timeseries&from_ts=1695626964048&to_ts=1695627864048&live=true
while we are figuring out the root case of the error
=> fix: error

src/components/icons/RocketIcon.tsx, src/components/icons/index.ts
Adding rocket icon
N/A
:rocket:
https://zbiljic-add-rocket-icon-components-pkg.branch.autoscout24.dev/?path=/docs/foundations-icons--docs
=> feat: adding rocket icon

src/components/filterPatterns/modal/index.stories.mdx, src/components/filterPatterns/modal/index.tsx, src/components/filterPatterns/popover/Popover.tsx, src/components/filterPatterns/popover/index.stories.mdx
References [DM-1993](https://autoricardo.atlassian.net/browse/DM-1993)
Prevent overlapping scrollbar and facets when user is scrolling.
[DM-1993]: https://autoricardo.atlassian.net/browse/DM-1993?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix scrollbar position

src/components/navigation/header/config/DrawerNodeItems.tsx, src/components/navigation/header/index.stories.mdx, src/types/entitlements.ts
References https://autoricardo.atlassian.net/browse/VSST-1722
Adding MarketPriceCheck link
No MarketPriceCheck
MarketPriceCheck ✅ 
https://zbiljic-marketprice-check-components-pkg.branch.autoscout24.dev/?path=/story/patterns-navigation-header--professional
=> feat: adding MarketPriceCheck link

src/components/drawer/DrawerBody.tsx, src/components/drawer/DrawerContent.tsx, src/components/drawer/index.stories.mdx, src/components/index.ts, src/themes/components/drawer.ts
https://autoricardo.atlassian.net/browse/IN-1072
Extend drawer with `DrawerBody` and `DrawerCloseButton` components.
https://fix-drawer-components-pkg.branch.autoscout24.dev/?path=/story/components-data-display-drawer--drawer
=> fix: extend drawer with body and close btn

src/components/datePicker/index.stories.mdx, src/components/datePicker/index.tsx
References [JIRA](https://autoricardo.atlassian.net/browse/IN-1432)
We need a way to highlight field and show error message for datepicker.
Datepicker component doesn't have invalid state.
Datepicker component has a prop to toggle its invalid state.
=> feat: add invalid state to datepicker

src/components/filterPatterns/popover/Popover.tsx, src/components/filterPatterns/popover/index.stories.mdx
References https://autoricardo.atlassian.net/browse/DM-2542
The content should be allowed to have the height as if the call to action button would be there.
=> feat: increase popover max height when no cta is present

src/components/filterPatterns/popover/Popover.tsx
References [[link the ticket here](https://autoricardo.atlassian.net/browse/DM-2541)]
Increase shadow for popover filter.
=> fix: increase popover shadow sm->md

src/components/filterPatterns/modal/OpenFilterButton.tsx, src/components/filterPatterns/modal/index.tsx, src/components/filterPatterns/modal/props.ts, src/locales/fr/dict.json
References [DM-2491](https://autoricardo.atlassian.net/browse/DM-2491)
Add `isDisabled` prop to `OpenFilterButton`
No isDisabled prop
With isDisabledProp
[DM-2491]: https://autoricardo.atlassian.net/browse/DM-2491?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: add isDisabled prop to button

src/components/filterPatterns/popover/__tests__/Index.Test.tsx, src/components/filterPatterns/popover/index.tsx
=> fix: disable button when popover is opened

src/components/checkboxFilter/StoryTemplate.tsx, src/components/checkboxFilter/index.tsx, src/components/index.ts, src/components/text/HighlightedText.tsx, src/components/text/index.stories.mdx
References https://autoricardo.atlassian.net/browse/DM-2559
We add filter capability to one of our checkbox filters. Therefore we extract the highlight text component that we have in listings-web
See here: https://github.com/smg-automotive/listings-web/pull/1779
=> feat: port highlighted text from listings-web

.github/workflows/assign-reviewers-phrase.yml
=> chore: fix assign reviewer Phrase GH action

src/components/rangeFilterInputWithSlider/__tests__/Index.Test.tsx, src/components/rangeFilterInputWithSlider/index.tsx
[Ticket](https://smg-au.atlassian.net/browse/DM-2724)
Adds additional field to distinguish change on input and on slider release, mainly for tracking purposes.
=> fix: add indicator of change for range filter

src/components/checkboxFilter/index.tsx
References https://smg-au.atlassian.net/browse/DM-2804
=> feat: change facet color

src/components/checkboxFilter/index.tsx
References https://smg-au.atlassian.net/browse/DM-2803
At the moment we have the checkbox and the label centered and the faceted number is top-aligned. 
To build a better visual alignment, we want to align every element to the top: Checkbox, label, and faceted number.
Please check the result on the listings PR where it describes how to test it -> https://github.com/smg-automotive/listings-web/pull/1903
=> fix: adjusted checkbox filter alignment

src/components/icons/LockIcon.tsx, src/components/icons/index.ts
=> feat: adding lock icon

src/components/filterPatterns/popover/__tests__/Index.Test.tsx, src/components/filterPatterns/popover/index.stories.mdx, src/components/filterPatterns/popover/index.tsx
[Ticket](https://smg-au.atlassian.net/browse/DM-2650)
This adds check for display value since we want to show the applied filters only when the filters are actually applied and not when user clicks and goes through them. For that part we rely on `displayValue` that's being passed to this component but the logic for `displayValue` should remain on the project level.
=> Fix filter display value new

src/themes/components/tabs.ts
References [JIRA](https://smg-au.atlassian.net/browse/FE-231)
Improve tabs UI: increase selected tab border width, increase tab padding, replace disabled state opacity with colour token.
Selected tab border 1px, padding 8px, disabled state set through opacity.
Selected tab border 2px, padding 12px, disabled state set through colour token.
URL: https://improve-tabs-components-pkg.branch.autoscout24.dev/?path=/docs/components-navigation-tabs--docs
=> fix: improve tabs ui

.circleci/config.yml
References https://smg-au.atlassian.net/browse/FE-211
Bumps the remote docker image to the latest version
=> chore: bump remote docker image

src/themes/components/checkbox.ts
References https://smg-au.atlassian.net/browse/DM-2754
Design: https://www.figma.com/file/CHU4fpMfXpiAW4qNFzi9y1/11.-AS24---Web---Components?type=design&node-id=4-5607&mode=design&t=eLTLYQ8wSA56JJWM-0
Change the checkbox style
Please check all the states on the checkbox, checkboxGroup and the indeterminate.
=> fix: adjusted checkbox styles

src/components/icons/HistoryClockIcon.tsx, src/components/icons/index.ts
New icon needed for the last searches feature
=> feat: add history clock icon

src/components/navigation/header/config/DrawerNodeItems.tsx, src/locales/de/dict.json, src/locales/en/dict.json, src/locales/fr/dict.json, src/locales/it/dict.json
We missed this on SRP release :)
=> fix: remove last searches link in header

src/components/navigation/header/config/DrawerNodeItems.tsx, src/locales/de/dict.json, src/locales/en/dict.json, src/locales/fr/dict.json, src/locales/it/dict.json
References [DM-2925](https://smg-au.atlassian.net/browse/DM-2925)
=> fix: remove findPartsAndAccessories item from header

src/themes/components/checkbox.ts
Change the outline pixels from `3px - 2px`
Please check the hover and focus state that has 2px as outline
=> fix: changed outline pixels

src/components/formControl/index.stories.tsx
UX-Designers are confused when they check the Form Control in StoryBook. They think, they can manipulate the sizes for the children through the Form Control.
To clarify this, I added a text.
=> chore: added some text for clarification

src/components/filterPatterns/popover/index.tsx
References https://smg-au.atlassian.net/browse/DM-3035
Please check the popover variations: with icon, with label, with long label, etc
=> fix: recovered our ellipsis friend

src/themes/components/slider.ts
[Ticket](https://smg-au.atlassian.net/browse/DM-2834)
Designers want stronger visual feedback on active slider state.
=> fix: range slider active state

src/locales/it/dict.json
Exported the most recent locale files from Phrase
=> fix: Updated translations from Phrase

src/components/icons/ChatBubbleIcon.tsx, src/components/icons/index.ts
Adding chat bubble icon in order to use it on new cockpit page.
https://chat-bubble-icon-components-pkg.branch.autoscout24.dev/?path=/docs/foundations-icons--documentation
=> feat: adding chat bubble icon

src/components/icons/CompareIcon.tsx, src/components/icons/index.ts
Will need this for various things about the comparison tool
=> feat: add compare icon

src/components/navigation/header/config/DrawerNodeItems.tsx
References https://smg-au.atlassian.net/browse/DM-3151
New saved searches page has been released to production 100%
=> fix: update saved searches url to new stack format

src/components/navigation/header/config/DrawerNodeItems.tsx
=> fix: set is new flag on comparison header item

src/components/tab/TabPanel.tsx, src/themes/components/tabs.ts
References https://smg-au.atlassian.net/browse/ST-77
Adding margin prop to tab panel component.
=> feat: tabpanel margin

src/components/articleTeaser/index.tsx, src/components/stack/index.tsx
References https://smg-au.atlassian.net/browse/DM-3444
go to https://www.autoscout24.ch/it/ld/listings/11762647/message-lead/success on a large mobile/tablet
nicely left aligned
=> fix: article width

src/components/navigation/header/index.stories.tsx
=> fix: remove shopping card

src/components/carousel/Slide.tsx, src/components/carousel/index.stories.tsx, src/components/carousel/index.tsx, src/themes/components/carousel.ts
Adjustments needed to support multiple slides on a single carousel page for the new AI recommendations
https://talamcol-ai-carousel-listings-web.branch.autoscout24.dev/de/ld/listings/8680706/message-lead/success
=> feat: allow to show multiple slides per view in the carousel

src/components/carousel/Slide.tsx, src/components/carousel/index.stories.tsx, src/components/carousel/index.tsx, src/themes/components/carousel.ts
Reverts smg-automotive/components-pkg#1119
=> fix: revert slides per view change

src/locales/de/dict.json, src/locales/fr/dict.json, src/locales/it/dict.json
Exported the most recent locale files from Phrase
=> fix(translations): Updated translations from Phrase

src/themes/components/switch.ts
Window is not defined, reference -> https://app.circleci.com/pipelines/github/smg-automotive/hci-web/77/workflows/2f6390cd-862a-4aa8-9e0d-72f5d4cef839/jobs/505
=> fix: Fix window is not defined and remove unnecessary svg.

src/components/icons/ChfCurrencyIcon.tsx, src/components/icons/PriceIcon.tsx, src/components/icons/index.ts
References [IN-2305](https://smg-au.atlassian.net/browse/IN-2305)
We want to use Price icon for Price column in listing table header in vehicle pool.
[IN-2305]: https://smg-au.atlassian.net/browse/IN-2305?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add price icon

src/components/icons/FlameIcon.tsx, src/components/icons/index.ts
=> feat: flame icon

src/components/icons/BulbIcon.tsx, src/components/icons/index.ts
Adding bulb icon.
https://bulb-icon-components-pkg.branch.autoscout24.dev/?path=/docs/foundations-icons--documentation
=> feat: adding bulb icon

src/components/icons/NoPhotoIcon.tsx, src/components/icons/ThumbsDownIcon.tsx, src/components/icons/ThumbsUpIcon.tsx, src/components/icons/index.ts
References https://smg-au.atlassian.net/browse/ST-469
Adding icons needed for smart insights. 
https://www.figma.com/design/JIg3a2e1WTSGRm0UBF9Hc5/Dealer-Dashboard-2024?node-id=5027-17427&node-type=frame&t=NELdeTkebvyZ1CHF-0
=> feat: icons

src/locales/de/dict.json
=> chore: test

.github/workflows/phrase-keys-added.yml, src/locales/de/dict.json
References https://smg-au.atlassian.net/browse/DM-3639
Port changes from https://github.com/smg-automotive/listings-web/pull/2719
I also created a tech ticket to share the github actions in the future: https://smg-au.atlassian.net/browse/FED-419
=> chore: add notification when translations are added

src/components/navigation/header/config/DrawerNodeItems.tsx
=> fix: ms entitlement to hide dealerdashboard

src/themes/components/slider.ts
References https://automotivesmg.slack.com/archives/C034EGP8GG0/p1732038267539229
Adds the missing slider-thumb-size variable
Slider was broken 
Sliders are working again as intended
Check the slider variations
=> fix: add missing varable

src/components/navigation/header/config/DrawerNodeItems.tsx
References [JIRA](https://smg-au.atlassian.net/browse/DM-3700)
As we released favorites page to prod env we need to cleanup links pointing to legacy.
=> chore: Cleanup favorites links.

src/components/navigation/header/config/DrawerNodeItems.tsx
References https://smg-au.atlassian.net/browse/SST-1067
This is a coordinated release and can only be released after the professional user auth0 release scheduled for the 10.12
Updates and activates the change email link for everyone everywhere
=> feat(change-email-link): activate for all users and update paths

src/components/navigation/header/config/DrawerNodeItems.tsx
References [VSST-2855](https://smg-au.atlassian.net/browse/VSST-2855)
Change header link to accomodate redirection to new professional profile page
[VSST-2855]: https://smg-au.atlassian.net/browse/VSST-2855?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> refactor: change header link for profile page

src/components/navigation/link.ts
=> fix: move condition to prefixDomain

src/components/navigation/header/config/DrawerNodeItems.tsx, src/types/entitlements.ts
=> fix: remove cockpit-frontend entitlement

src/components/mobileOnlyAccordion/index.tsx, src/components/navigation/header/__tests__/index.Test.tsx, src/components/navigation/header/drawer/index.tsx, src/components/navigation/header/drawer/userInfo/SelectedTenantInfo.tsx, src/components/navigation/header/drawer/userInfo/TenantSelectionMenu.tsx, src/components/navigation/header/drawer/userInfo/index.tsx, src/components/navigation/header/index.stories.tsx, src/components/navigation/header/index.tsx, src/components/navigation/header/navigationTenantMenu/Content.tsx, src/components/navigation/header/navigationTenantMenu/Loading.tsx, src/components/navigation/header/navigationTenantMenu/index.tsx, src/components/tenantSelection/select/List.tsx
References https://smg-au.atlassian.net/browse/FED-597
Design: https://www.figma.com/design/u9kHtjsYjfWFBcmENxK27B/New-Login-(private-%26-professionals)---Auth0?node-id=1868-11754&t=g3etBSGeIjK3NbTR-4
Adds a mobile variant of the tenant selection menu to the combined drawer
This pull request introduces significant changes to the tenant selection functionality in the navigation header. The changes include adding new components and modifying existing ones to support tenant selection in both desktop and mobile views.
* [`src/components/navigation/header/drawer/index.tsx`](diffhunk://#diff-4726278a2d58671e697a1492dc4cbea0a87f69cd57a50aecb323f5548de42fefR25): Added `selectTenant` prop to `NavigationDrawerProps` and passed it to `DrawerUserInfo`. …
=> feat: tenant selection on mobile

src/components/navigation/header/drawer/index.tsx, src/components/navigation/header/index.stories.tsx, src/components/navigation/header/index.tsx, src/components/navigation/header/navigationTenantMenu/index.tsx, src/components/tenantSelection/ModalLayout.tsx, src/components/tenantSelection/index.stories.tsx
FIxes the positioning and display issues with the tenant selection when there are many sellers:
- properly set overflows on the searchable list
- increases spacing on mobile to accommodate for iOS scrolling behaviour on the tenant selection modal
- changes the header positioning and spacing to fix the issues with iOS safari pushing the content upwards when input is focused
This pull request includes several changes to improve the navigation components and tenant selection modal in the project. The most important changes include adjustments to the `NavigationDrawer` component, updates to the storybook for the navigation header, and enhancements to the tenant selection modal layout.
* [`src/components/navigation/header/drawer/index.tsx`](diffhunk://#diff-4726278a2d58671e697a1492dc4cbea0a87f6 …
=> fix: properly set the overflows and heights for the tenant selection

src/components/navigation/header/config/user.ts
References https://smg-au.atlassian.net/browse/FED-631
Features:
https://github.com/smg-automotive/seller-web/pull/3055
https://github.com/smg-automotive/seller-web/pull/3046
Infra:
https://github.com/smg-automotive/terraform-cloudflare/pull/751
Updates the link for the re-plattformed account pages
=> fix: update account page links

src/components/index.ts, src/components/linkOverlay/index.stories.tsx, src/components/linkOverlay/index.tsx
References https://smg-au.atlassian.net/browse/DM-4128
Works super well on HCI, we would like to use it on AutoRadar as well
https://v2.chakra-ui.com/docs/components/link-overlay/usage#usage-with-routing-library
https://talamcol-link-box-components-pkg.branch.autoscout24.dev/?path=/docs/components-utils-linkoverlay--documentation
=> feat: export link box and link overlay from chakra

src/components/checkboxFilter/CheckboxWithFacet.tsx, src/components/checkboxFilter/type.ts
References https://smg-au.atlassian.net/browse/DM-4337
For AutoRadar, we won't show facets. This PR makes facet optional and only renders it when it's a number
=> feat: make facet optional on checkbox filter

src/components/icons/TimeIcon.tsx
=> fix: adjust time icon colors to match currentColor

src/components/index.ts, src/components/timePicker/__tests__/TimePicker.Test.tsx, src/components/timePicker/index.stories.tsx, src/components/timePicker/index.tsx
References [VSST-3622](https://smg-au.atlassian.net/browse/VSST-3622)
Create time picker component
It was not implemented
[VSST-3622]: https://smg-au.atlassian.net/browse/VSST-3622?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: create time picker component

src/components/icons/OverflowVerticalIcon.tsx, src/components/icons/index.ts
Used for menu button on AutoRadar
=> feat: create overflow icon

package-lock.json, package.json
References
https://github.com/smg-automotive/listings-web/pull/3235
https://smg-au.atlassian.net/browse/FED-769
https://smg-au.atlassian.net/browse/FED-771
Update to version with reverted rosetta change
=> fix: install reverted i18n version

package-lock.json, package.json, src/components/navigation/footer/config/index.ts, src/components/navigation/footer/index.tsx
Updating to latest 23.x version
=> Update latest changes form 23.x version

src/components/errorPage/actions/primary/BackToLogin.tsx
References https://smg-au.atlassian.net/browse/FED-557
Update the logout and login link to use the new auth0 implementation.
For simplicity using the one on seller web with the proxy path. manually tested on localhost
=> feat: swap logout links on error page

rollup.config.mjs, src/lib/cli/index.ts
References https://app.circleci.com/pipelines/github/smg-automotive/seller-web/19906/workflows/bb0b5d70-d33a-4644-8c03-6f632c93b554/jobs/144495
=> fix: yargs usage in cli after update

src/components/navigation/header/config/advertise.ts
References [VSST-3928](https://smg-au.atlassian.net/browse/VSST-3928)
[VSST-3928]: https://smg-au.atlassian.net/browse/VSST-3928?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: advertising header link

src/components/navigation/header/config/Optimizer.tsx
=> fix: optimizer b2b link
